// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item/ItemFaceMsg.proto

package com.chuangyou.common.protobuf.pb.item;

public final class ItemFaceMsgProto {
  private ItemFaceMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemFaceMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ItemFaceMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 templateId = 1;</code>
     *
     * <pre>
     * 模板ID
     * </pre>
     */
    boolean hasTemplateId();
    /**
     * <code>optional int32 templateId = 1;</code>
     *
     * <pre>
     * 模板ID
     * </pre>
     */
    int getTemplateId();

    /**
     * <code>optional int32 pos = 2;</code>
     *
     * <pre>
     * 位置
     * </pre>
     */
    boolean hasPos();
    /**
     * <code>optional int32 pos = 2;</code>
     *
     * <pre>
     * 位置
     * </pre>
     */
    int getPos();

    /**
     * <code>optional int32 bagType = 3;</code>
     *
     * <pre>
     *背包类型
     * </pre>
     */
    boolean hasBagType();
    /**
     * <code>optional int32 bagType = 3;</code>
     *
     * <pre>
     *背包类型
     * </pre>
     */
    int getBagType();

    /**
     * <code>optional bool bind = 4;</code>
     *
     * <pre>
     *是否绑定
     * </pre>
     */
    boolean hasBind();
    /**
     * <code>optional bool bind = 4;</code>
     *
     * <pre>
     *是否绑定
     * </pre>
     */
    boolean getBind();

    /**
     * <code>optional int32 count = 5;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 5;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code ItemFaceMsg}
   *
   * <pre>
   *物品外观
   * </pre>
   */
  public static final class ItemFaceMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ItemFaceMsg)
      ItemFaceMsgOrBuilder {
    // Use ItemFaceMsg.newBuilder() to construct.
    private ItemFaceMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemFaceMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemFaceMsg defaultInstance;
    public static ItemFaceMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ItemFaceMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemFaceMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              templateId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pos_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              bagType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              bind_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.internal_static_ItemFaceMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.internal_static_ItemFaceMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.class, com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemFaceMsg> PARSER =
        new com.google.protobuf.AbstractParser<ItemFaceMsg>() {
      public ItemFaceMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemFaceMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemFaceMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEMPLATEID_FIELD_NUMBER = 1;
    private int templateId_;
    /**
     * <code>optional int32 templateId = 1;</code>
     *
     * <pre>
     * 模板ID
     * </pre>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 templateId = 1;</code>
     *
     * <pre>
     * 模板ID
     * </pre>
     */
    public int getTemplateId() {
      return templateId_;
    }

    public static final int POS_FIELD_NUMBER = 2;
    private int pos_;
    /**
     * <code>optional int32 pos = 2;</code>
     *
     * <pre>
     * 位置
     * </pre>
     */
    public boolean hasPos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pos = 2;</code>
     *
     * <pre>
     * 位置
     * </pre>
     */
    public int getPos() {
      return pos_;
    }

    public static final int BAGTYPE_FIELD_NUMBER = 3;
    private int bagType_;
    /**
     * <code>optional int32 bagType = 3;</code>
     *
     * <pre>
     *背包类型
     * </pre>
     */
    public boolean hasBagType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 bagType = 3;</code>
     *
     * <pre>
     *背包类型
     * </pre>
     */
    public int getBagType() {
      return bagType_;
    }

    public static final int BIND_FIELD_NUMBER = 4;
    private boolean bind_;
    /**
     * <code>optional bool bind = 4;</code>
     *
     * <pre>
     *是否绑定
     * </pre>
     */
    public boolean hasBind() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool bind = 4;</code>
     *
     * <pre>
     *是否绑定
     * </pre>
     */
    public boolean getBind() {
      return bind_;
    }

    public static final int COUNT_FIELD_NUMBER = 5;
    private int count_;
    /**
     * <code>optional int32 count = 5;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 count = 5;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      templateId_ = 0;
      pos_ = 0;
      bagType_ = 0;
      bind_ = false;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, templateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, bagType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, bind_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, templateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bagType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, bind_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemFaceMsg}
     *
     * <pre>
     *物品外观
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ItemFaceMsg)
        com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.internal_static_ItemFaceMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.internal_static_ItemFaceMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.class, com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        templateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bagType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        bind_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.internal_static_ItemFaceMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg build() {
        com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg result = new com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.templateId_ = templateId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pos_ = pos_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bagType_ = bagType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bind_ = bind_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg.getDefaultInstance()) return this;
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        if (other.hasPos()) {
          setPos(other.getPos());
        }
        if (other.hasBagType()) {
          setBagType(other.getBagType());
        }
        if (other.hasBind()) {
          setBind(other.getBind());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.item.ItemFaceMsgProto.ItemFaceMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int templateId_ ;
      /**
       * <code>optional int32 templateId = 1;</code>
       *
       * <pre>
       * 模板ID
       * </pre>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 templateId = 1;</code>
       *
       * <pre>
       * 模板ID
       * </pre>
       */
      public int getTemplateId() {
        return templateId_;
      }
      /**
       * <code>optional int32 templateId = 1;</code>
       *
       * <pre>
       * 模板ID
       * </pre>
       */
      public Builder setTemplateId(int value) {
        bitField0_ |= 0x00000001;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 templateId = 1;</code>
       *
       * <pre>
       * 模板ID
       * </pre>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        templateId_ = 0;
        onChanged();
        return this;
      }

      private int pos_ ;
      /**
       * <code>optional int32 pos = 2;</code>
       *
       * <pre>
       * 位置
       * </pre>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pos = 2;</code>
       *
       * <pre>
       * 位置
       * </pre>
       */
      public int getPos() {
        return pos_;
      }
      /**
       * <code>optional int32 pos = 2;</code>
       *
       * <pre>
       * 位置
       * </pre>
       */
      public Builder setPos(int value) {
        bitField0_ |= 0x00000002;
        pos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pos = 2;</code>
       *
       * <pre>
       * 位置
       * </pre>
       */
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pos_ = 0;
        onChanged();
        return this;
      }

      private int bagType_ ;
      /**
       * <code>optional int32 bagType = 3;</code>
       *
       * <pre>
       *背包类型
       * </pre>
       */
      public boolean hasBagType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 bagType = 3;</code>
       *
       * <pre>
       *背包类型
       * </pre>
       */
      public int getBagType() {
        return bagType_;
      }
      /**
       * <code>optional int32 bagType = 3;</code>
       *
       * <pre>
       *背包类型
       * </pre>
       */
      public Builder setBagType(int value) {
        bitField0_ |= 0x00000004;
        bagType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bagType = 3;</code>
       *
       * <pre>
       *背包类型
       * </pre>
       */
      public Builder clearBagType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bagType_ = 0;
        onChanged();
        return this;
      }

      private boolean bind_ ;
      /**
       * <code>optional bool bind = 4;</code>
       *
       * <pre>
       *是否绑定
       * </pre>
       */
      public boolean hasBind() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool bind = 4;</code>
       *
       * <pre>
       *是否绑定
       * </pre>
       */
      public boolean getBind() {
        return bind_;
      }
      /**
       * <code>optional bool bind = 4;</code>
       *
       * <pre>
       *是否绑定
       * </pre>
       */
      public Builder setBind(boolean value) {
        bitField0_ |= 0x00000008;
        bind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bind = 4;</code>
       *
       * <pre>
       *是否绑定
       * </pre>
       */
      public Builder clearBind() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bind_ = false;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 5;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 count = 5;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 5;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000010;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 5;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemFaceMsg)
    }

    static {
      defaultInstance = new ItemFaceMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemFaceMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemFaceMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemFaceMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026item/ItemFaceMsg.proto\"\\\n\013ItemFaceMsg\022" +
      "\022\n\ntemplateId\030\001 \001(\005\022\013\n\003pos\030\002 \001(\005\022\017\n\007bagT" +
      "ype\030\003 \001(\005\022\014\n\004bind\030\004 \001(\010\022\r\n\005count\030\005 \001(\005B9" +
      "\n%com.chuangyou.common.protobuf.pb.itemB" +
      "\020ItemFaceMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ItemFaceMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ItemFaceMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ItemFaceMsg_descriptor,
        new java.lang.String[] { "TemplateId", "Pos", "BagType", "Bind", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
