// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state/GetStateInfoRespMsg.proto

package com.chuangyou.common.protobuf.pb.state;

public final class GetStateInfoRespProto {
  private GetStateInfoRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetStateInfoRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetStateInfoRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> 
        getInfosList();
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg getInfos(int index);
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    java.util.List<? extends com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder getInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetStateInfoRespMsg}
   *
   * <pre>
   *回复请求境界任务状态
   * </pre>
   */
  public static final class GetStateInfoRespMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetStateInfoRespMsg)
      GetStateInfoRespMsgOrBuilder {
    // Use GetStateInfoRespMsg.newBuilder() to construct.
    private GetStateInfoRespMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetStateInfoRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetStateInfoRespMsg defaultInstance;
    public static GetStateInfoRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public GetStateInfoRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetStateInfoRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                infos_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(input.readMessage(com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.internal_static_GetStateInfoRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.internal_static_GetStateInfoRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.class, com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<GetStateInfoRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<GetStateInfoRespMsg>() {
      public GetStateInfoRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetStateInfoRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetStateInfoRespMsg> getParserForType() {
      return PARSER;
    }

    public static final int INFOS_FIELD_NUMBER = 1;
    private java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> infos_;
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    public java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    public java.util.List<? extends com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .StateInfoMsg infos = 1;</code>
     */
    public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    private void initFields() {
      infos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getInfosCount(); i++) {
        if (!getInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(1, infos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, infos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetStateInfoRespMsg}
     *
     * <pre>
     *回复请求境界任务状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetStateInfoRespMsg)
        com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.internal_static_GetStateInfoRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.internal_static_GetStateInfoRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.class, com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.internal_static_GetStateInfoRespMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg build() {
        com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg result = new com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg(this);
        int from_bitField0_ = bitField0_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg.getDefaultInstance()) return this;
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInfosCount(); i++) {
          if (!getInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.state.GetStateInfoRespProto.GetStateInfoRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg>(infos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder> infosBuilder_;

      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder addInfos(com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder addInfos(
          com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public java.util.List<? extends com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .StateInfoMsg infos = 1;</code>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsg.Builder, com.chuangyou.common.protobuf.pb.state.StateInfoProto.StateInfoMsgOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GetStateInfoRespMsg)
    }

    static {
      defaultInstance = new GetStateInfoRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetStateInfoRespMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetStateInfoRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetStateInfoRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037state/GetStateInfoRespMsg.proto\032\030state" +
      "/StateInfoMsg.proto\"3\n\023GetStateInfoRespM" +
      "sg\022\034\n\005infos\030\001 \003(\0132\r.StateInfoMsgB?\n&com." +
      "chuangyou.common.protobuf.pb.stateB\025GetS" +
      "tateInfoRespProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chuangyou.common.protobuf.pb.state.StateInfoProto.getDescriptor(),
        }, assigner);
    internal_static_GetStateInfoRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetStateInfoRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetStateInfoRespMsg_descriptor,
        new java.lang.String[] { "Infos", });
    com.chuangyou.common.protobuf.pb.state.StateInfoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
