// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state/NotifyStateQteMsg.proto

package com.chuangyou.common.protobuf.pb.state;

public final class NotifyStateQteProto {
  private NotifyStateQteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotifyStateQteMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotifyStateQteMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 qteId = 1;</code>
     *
     * <pre>
     *qteID
     * </pre>
     */
    boolean hasQteId();
    /**
     * <code>required int32 qteId = 1;</code>
     *
     * <pre>
     *qteID
     * </pre>
     */
    int getQteId();

    /**
     * <code>required int32 qteLimitTime = 2;</code>
     *
     * <pre>
     *QTE限时（单位：秒）
     * </pre>
     */
    boolean hasQteLimitTime();
    /**
     * <code>required int32 qteLimitTime = 2;</code>
     *
     * <pre>
     *QTE限时（单位：秒）
     * </pre>
     */
    int getQteLimitTime();

    /**
     * <code>required int32 eventId = 3;</code>
     *
     * <pre>
     *事件相关
     * </pre>
     */
    boolean hasEventId();
    /**
     * <code>required int32 eventId = 3;</code>
     *
     * <pre>
     *事件相关
     * </pre>
     */
    int getEventId();
  }
  /**
   * Protobuf type {@code NotifyStateQteMsg}
   *
   * <pre>
   *通知执行QTE
   * </pre>
   */
  public static final class NotifyStateQteMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NotifyStateQteMsg)
      NotifyStateQteMsgOrBuilder {
    // Use NotifyStateQteMsg.newBuilder() to construct.
    private NotifyStateQteMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotifyStateQteMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotifyStateQteMsg defaultInstance;
    public static NotifyStateQteMsg getDefaultInstance() {
      return defaultInstance;
    }

    public NotifyStateQteMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyStateQteMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              qteId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              qteLimitTime_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              eventId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.internal_static_NotifyStateQteMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.internal_static_NotifyStateQteMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.class, com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<NotifyStateQteMsg> PARSER =
        new com.google.protobuf.AbstractParser<NotifyStateQteMsg>() {
      public NotifyStateQteMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyStateQteMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyStateQteMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int QTEID_FIELD_NUMBER = 1;
    private int qteId_;
    /**
     * <code>required int32 qteId = 1;</code>
     *
     * <pre>
     *qteID
     * </pre>
     */
    public boolean hasQteId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 qteId = 1;</code>
     *
     * <pre>
     *qteID
     * </pre>
     */
    public int getQteId() {
      return qteId_;
    }

    public static final int QTELIMITTIME_FIELD_NUMBER = 2;
    private int qteLimitTime_;
    /**
     * <code>required int32 qteLimitTime = 2;</code>
     *
     * <pre>
     *QTE限时（单位：秒）
     * </pre>
     */
    public boolean hasQteLimitTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 qteLimitTime = 2;</code>
     *
     * <pre>
     *QTE限时（单位：秒）
     * </pre>
     */
    public int getQteLimitTime() {
      return qteLimitTime_;
    }

    public static final int EVENTID_FIELD_NUMBER = 3;
    private int eventId_;
    /**
     * <code>required int32 eventId = 3;</code>
     *
     * <pre>
     *事件相关
     * </pre>
     */
    public boolean hasEventId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 eventId = 3;</code>
     *
     * <pre>
     *事件相关
     * </pre>
     */
    public int getEventId() {
      return eventId_;
    }

    private void initFields() {
      qteId_ = 0;
      qteLimitTime_ = 0;
      eventId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQteId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQteLimitTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, qteId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, qteLimitTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, eventId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, qteId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, qteLimitTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, eventId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotifyStateQteMsg}
     *
     * <pre>
     *通知执行QTE
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotifyStateQteMsg)
        com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.internal_static_NotifyStateQteMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.internal_static_NotifyStateQteMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.class, com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        qteId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        qteLimitTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        eventId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.internal_static_NotifyStateQteMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg build() {
        com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg result = new com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.qteId_ = qteId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qteLimitTime_ = qteLimitTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.eventId_ = eventId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg.getDefaultInstance()) return this;
        if (other.hasQteId()) {
          setQteId(other.getQteId());
        }
        if (other.hasQteLimitTime()) {
          setQteLimitTime(other.getQteLimitTime());
        }
        if (other.hasEventId()) {
          setEventId(other.getEventId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQteId()) {
          
          return false;
        }
        if (!hasQteLimitTime()) {
          
          return false;
        }
        if (!hasEventId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.state.NotifyStateQteProto.NotifyStateQteMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int qteId_ ;
      /**
       * <code>required int32 qteId = 1;</code>
       *
       * <pre>
       *qteID
       * </pre>
       */
      public boolean hasQteId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 qteId = 1;</code>
       *
       * <pre>
       *qteID
       * </pre>
       */
      public int getQteId() {
        return qteId_;
      }
      /**
       * <code>required int32 qteId = 1;</code>
       *
       * <pre>
       *qteID
       * </pre>
       */
      public Builder setQteId(int value) {
        bitField0_ |= 0x00000001;
        qteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 qteId = 1;</code>
       *
       * <pre>
       *qteID
       * </pre>
       */
      public Builder clearQteId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        qteId_ = 0;
        onChanged();
        return this;
      }

      private int qteLimitTime_ ;
      /**
       * <code>required int32 qteLimitTime = 2;</code>
       *
       * <pre>
       *QTE限时（单位：秒）
       * </pre>
       */
      public boolean hasQteLimitTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 qteLimitTime = 2;</code>
       *
       * <pre>
       *QTE限时（单位：秒）
       * </pre>
       */
      public int getQteLimitTime() {
        return qteLimitTime_;
      }
      /**
       * <code>required int32 qteLimitTime = 2;</code>
       *
       * <pre>
       *QTE限时（单位：秒）
       * </pre>
       */
      public Builder setQteLimitTime(int value) {
        bitField0_ |= 0x00000002;
        qteLimitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 qteLimitTime = 2;</code>
       *
       * <pre>
       *QTE限时（单位：秒）
       * </pre>
       */
      public Builder clearQteLimitTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        qteLimitTime_ = 0;
        onChanged();
        return this;
      }

      private int eventId_ ;
      /**
       * <code>required int32 eventId = 3;</code>
       *
       * <pre>
       *事件相关
       * </pre>
       */
      public boolean hasEventId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 eventId = 3;</code>
       *
       * <pre>
       *事件相关
       * </pre>
       */
      public int getEventId() {
        return eventId_;
      }
      /**
       * <code>required int32 eventId = 3;</code>
       *
       * <pre>
       *事件相关
       * </pre>
       */
      public Builder setEventId(int value) {
        bitField0_ |= 0x00000004;
        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 eventId = 3;</code>
       *
       * <pre>
       *事件相关
       * </pre>
       */
      public Builder clearEventId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NotifyStateQteMsg)
    }

    static {
      defaultInstance = new NotifyStateQteMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NotifyStateQteMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotifyStateQteMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NotifyStateQteMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035state/NotifyStateQteMsg.proto\"I\n\021Notif" +
      "yStateQteMsg\022\r\n\005qteId\030\001 \002(\005\022\024\n\014qteLimitT" +
      "ime\030\002 \002(\005\022\017\n\007eventId\030\003 \002(\005B=\n&com.chuang" +
      "you.common.protobuf.pb.stateB\023NotifyStat" +
      "eQteProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NotifyStateQteMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotifyStateQteMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NotifyStateQteMsg_descriptor,
        new java.lang.String[] { "QteId", "QteLimitTime", "EventId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
