// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OtherSoulMsg.proto

package com.chuangyou.common.protobuf.pb.player;

public final class OtherSoulgProto {
  private OtherSoulgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OtherSoulMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OtherSoulMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *½ÇÉ«ID
     * </pre>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *½ÇÉ«ID
     * </pre>
     */
    long getPlayerId();

    /**
     * <code>optional int32 card1 = 2;</code>
     *
     * <pre>
     *¿¨1
     * </pre>
     */
    boolean hasCard1();
    /**
     * <code>optional int32 card1 = 2;</code>
     *
     * <pre>
     *¿¨1
     * </pre>
     */
    int getCard1();

    /**
     * <code>optional int32 card2 = 3;</code>
     *
     * <pre>
     *¿¨2
     * </pre>
     */
    boolean hasCard2();
    /**
     * <code>optional int32 card2 = 3;</code>
     *
     * <pre>
     *¿¨2
     * </pre>
     */
    int getCard2();

    /**
     * <code>optional int32 card3 = 4;</code>
     *
     * <pre>
     *¿¨3
     * </pre>
     */
    boolean hasCard3();
    /**
     * <code>optional int32 card3 = 4;</code>
     *
     * <pre>
     *¿¨3
     * </pre>
     */
    int getCard3();

    /**
     * <code>optional int32 card4 = 5;</code>
     *
     * <pre>
     *¿¨4
     * </pre>
     */
    boolean hasCard4();
    /**
     * <code>optional int32 card4 = 5;</code>
     *
     * <pre>
     *¿¨4
     * </pre>
     */
    int getCard4();

    /**
     * <code>optional int32 card5 = 6;</code>
     *
     * <pre>
     *¿¨5
     * </pre>
     */
    boolean hasCard5();
    /**
     * <code>optional int32 card5 = 6;</code>
     *
     * <pre>
     *¿¨5
     * </pre>
     */
    int getCard5();

    /**
     * <code>optional int32 card6 = 7;</code>
     *
     * <pre>
     *¿¨6
     * </pre>
     */
    boolean hasCard6();
    /**
     * <code>optional int32 card6 = 7;</code>
     *
     * <pre>
     *¿¨6
     * </pre>
     */
    int getCard6();

    /**
     * <code>optional int32 card7 = 8;</code>
     *
     * <pre>
     *¿¨7
     * </pre>
     */
    boolean hasCard7();
    /**
     * <code>optional int32 card7 = 8;</code>
     *
     * <pre>
     *¿¨7
     * </pre>
     */
    int getCard7();

    /**
     * <code>optional int32 card8 = 9;</code>
     *
     * <pre>
     *¿¨8
     * </pre>
     */
    boolean hasCard8();
    /**
     * <code>optional int32 card8 = 9;</code>
     *
     * <pre>
     *¿¨8
     * </pre>
     */
    int getCard8();

    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> 
        getCardInfosList();
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg getCardInfos(int index);
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    int getCardInfosCount();
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    java.util.List<? extends com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder> 
        getCardInfosOrBuilderList();
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder getCardInfosOrBuilder(
        int index);

    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    boolean hasPropertitys();
    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg getPropertitys();
    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder getPropertitysOrBuilder();
  }
  /**
   * Protobuf type {@code OtherSoulMsg}
   */
  public static final class OtherSoulMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OtherSoulMsg)
      OtherSoulMsgOrBuilder {
    // Use OtherSoulMsg.newBuilder() to construct.
    private OtherSoulMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OtherSoulMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OtherSoulMsg defaultInstance;
    public static OtherSoulMsg getDefaultInstance() {
      return defaultInstance;
    }

    public OtherSoulMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OtherSoulMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              card1_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              card2_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              card3_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              card4_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              card5_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              card6_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              card7_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              card8_ = input.readInt32();
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                cardInfos_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg>();
                mutable_bitField0_ |= 0x00000200;
              }
              cardInfos_.add(input.readMessage(com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.PARSER, extensionRegistry));
              break;
            }
            case 90: {
              com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = propertitys_.toBuilder();
              }
              propertitys_ = input.readMessage(com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(propertitys_);
                propertitys_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          cardInfos_ = java.util.Collections.unmodifiableList(cardInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.internal_static_OtherSoulMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.internal_static_OtherSoulMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.class, com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<OtherSoulMsg> PARSER =
        new com.google.protobuf.AbstractParser<OtherSoulMsg>() {
      public OtherSoulMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OtherSoulMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OtherSoulMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *½ÇÉ«ID
     * </pre>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *½ÇÉ«ID
     * </pre>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int CARD1_FIELD_NUMBER = 2;
    private int card1_;
    /**
     * <code>optional int32 card1 = 2;</code>
     *
     * <pre>
     *¿¨1
     * </pre>
     */
    public boolean hasCard1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 card1 = 2;</code>
     *
     * <pre>
     *¿¨1
     * </pre>
     */
    public int getCard1() {
      return card1_;
    }

    public static final int CARD2_FIELD_NUMBER = 3;
    private int card2_;
    /**
     * <code>optional int32 card2 = 3;</code>
     *
     * <pre>
     *¿¨2
     * </pre>
     */
    public boolean hasCard2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 card2 = 3;</code>
     *
     * <pre>
     *¿¨2
     * </pre>
     */
    public int getCard2() {
      return card2_;
    }

    public static final int CARD3_FIELD_NUMBER = 4;
    private int card3_;
    /**
     * <code>optional int32 card3 = 4;</code>
     *
     * <pre>
     *¿¨3
     * </pre>
     */
    public boolean hasCard3() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 card3 = 4;</code>
     *
     * <pre>
     *¿¨3
     * </pre>
     */
    public int getCard3() {
      return card3_;
    }

    public static final int CARD4_FIELD_NUMBER = 5;
    private int card4_;
    /**
     * <code>optional int32 card4 = 5;</code>
     *
     * <pre>
     *¿¨4
     * </pre>
     */
    public boolean hasCard4() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 card4 = 5;</code>
     *
     * <pre>
     *¿¨4
     * </pre>
     */
    public int getCard4() {
      return card4_;
    }

    public static final int CARD5_FIELD_NUMBER = 6;
    private int card5_;
    /**
     * <code>optional int32 card5 = 6;</code>
     *
     * <pre>
     *¿¨5
     * </pre>
     */
    public boolean hasCard5() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 card5 = 6;</code>
     *
     * <pre>
     *¿¨5
     * </pre>
     */
    public int getCard5() {
      return card5_;
    }

    public static final int CARD6_FIELD_NUMBER = 7;
    private int card6_;
    /**
     * <code>optional int32 card6 = 7;</code>
     *
     * <pre>
     *¿¨6
     * </pre>
     */
    public boolean hasCard6() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 card6 = 7;</code>
     *
     * <pre>
     *¿¨6
     * </pre>
     */
    public int getCard6() {
      return card6_;
    }

    public static final int CARD7_FIELD_NUMBER = 8;
    private int card7_;
    /**
     * <code>optional int32 card7 = 8;</code>
     *
     * <pre>
     *¿¨7
     * </pre>
     */
    public boolean hasCard7() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 card7 = 8;</code>
     *
     * <pre>
     *¿¨7
     * </pre>
     */
    public int getCard7() {
      return card7_;
    }

    public static final int CARD8_FIELD_NUMBER = 9;
    private int card8_;
    /**
     * <code>optional int32 card8 = 9;</code>
     *
     * <pre>
     *¿¨8
     * </pre>
     */
    public boolean hasCard8() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 card8 = 9;</code>
     *
     * <pre>
     *¿¨8
     * </pre>
     */
    public int getCard8() {
      return card8_;
    }

    public static final int CARDINFOS_FIELD_NUMBER = 10;
    private java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> cardInfos_;
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    public java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> getCardInfosList() {
      return cardInfos_;
    }
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    public java.util.List<? extends com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder> 
        getCardInfosOrBuilderList() {
      return cardInfos_;
    }
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    public int getCardInfosCount() {
      return cardInfos_.size();
    }
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg getCardInfos(int index) {
      return cardInfos_.get(index);
    }
    /**
     * <code>repeated .CardInfoMsg cardInfos = 10;</code>
     *
     * <pre>
     *»êá¦ÏêÏ¸ÐÅÏ¢
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder getCardInfosOrBuilder(
        int index) {
      return cardInfos_.get(index);
    }

    public static final int PROPERTITYS_FIELD_NUMBER = 11;
    private com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg propertitys_;
    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    public boolean hasPropertitys() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg getPropertitys() {
      return propertitys_;
    }
    /**
     * <code>optional .PropertyListMsg propertitys = 11;</code>
     *
     * <pre>
     *»êá¦ÊôÐÔÁÐ±í
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder getPropertitysOrBuilder() {
      return propertitys_;
    }

    private void initFields() {
      playerId_ = 0L;
      card1_ = 0;
      card2_ = 0;
      card3_ = 0;
      card4_ = 0;
      card5_ = 0;
      card6_ = 0;
      card7_ = 0;
      card8_ = 0;
      cardInfos_ = java.util.Collections.emptyList();
      propertitys_ = com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCardInfosCount(); i++) {
        if (!getCardInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, card1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, card2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, card3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, card4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, card5_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, card6_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, card7_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, card8_);
      }
      for (int i = 0; i < cardInfos_.size(); i++) {
        output.writeMessage(10, cardInfos_.get(i));
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(11, propertitys_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, card1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, card2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, card3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, card4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, card5_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, card6_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, card7_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, card8_);
      }
      for (int i = 0; i < cardInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, cardInfos_.get(i));
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, propertitys_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OtherSoulMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OtherSoulMsg)
        com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.internal_static_OtherSoulMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.internal_static_OtherSoulMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.class, com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardInfosFieldBuilder();
          getPropertitysFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        card1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        card2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        card3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        card4_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        card5_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        card6_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        card7_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        card8_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (cardInfosBuilder_ == null) {
          cardInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          cardInfosBuilder_.clear();
        }
        if (propertitysBuilder_ == null) {
          propertitys_ = com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.getDefaultInstance();
        } else {
          propertitysBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.internal_static_OtherSoulMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg build() {
        com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg result = new com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.card1_ = card1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.card2_ = card2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.card3_ = card3_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.card4_ = card4_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.card5_ = card5_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.card6_ = card6_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.card7_ = card7_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.card8_ = card8_;
        if (cardInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            cardInfos_ = java.util.Collections.unmodifiableList(cardInfos_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.cardInfos_ = cardInfos_;
        } else {
          result.cardInfos_ = cardInfosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        if (propertitysBuilder_ == null) {
          result.propertitys_ = propertitys_;
        } else {
          result.propertitys_ = propertitysBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasCard1()) {
          setCard1(other.getCard1());
        }
        if (other.hasCard2()) {
          setCard2(other.getCard2());
        }
        if (other.hasCard3()) {
          setCard3(other.getCard3());
        }
        if (other.hasCard4()) {
          setCard4(other.getCard4());
        }
        if (other.hasCard5()) {
          setCard5(other.getCard5());
        }
        if (other.hasCard6()) {
          setCard6(other.getCard6());
        }
        if (other.hasCard7()) {
          setCard7(other.getCard7());
        }
        if (other.hasCard8()) {
          setCard8(other.getCard8());
        }
        if (cardInfosBuilder_ == null) {
          if (!other.cardInfos_.isEmpty()) {
            if (cardInfos_.isEmpty()) {
              cardInfos_ = other.cardInfos_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureCardInfosIsMutable();
              cardInfos_.addAll(other.cardInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.cardInfos_.isEmpty()) {
            if (cardInfosBuilder_.isEmpty()) {
              cardInfosBuilder_.dispose();
              cardInfosBuilder_ = null;
              cardInfos_ = other.cardInfos_;
              bitField0_ = (bitField0_ & ~0x00000200);
              cardInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCardInfosFieldBuilder() : null;
            } else {
              cardInfosBuilder_.addAllMessages(other.cardInfos_);
            }
          }
        }
        if (other.hasPropertitys()) {
          mergePropertitys(other.getPropertitys());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCardInfosCount(); i++) {
          if (!getCardInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.player.OtherSoulgProto.OtherSoulMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *½ÇÉ«ID
       * </pre>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *½ÇÉ«ID
       * </pre>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *½ÇÉ«ID
       * </pre>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *½ÇÉ«ID
       * </pre>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int card1_ ;
      /**
       * <code>optional int32 card1 = 2;</code>
       *
       * <pre>
       *¿¨1
       * </pre>
       */
      public boolean hasCard1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 card1 = 2;</code>
       *
       * <pre>
       *¿¨1
       * </pre>
       */
      public int getCard1() {
        return card1_;
      }
      /**
       * <code>optional int32 card1 = 2;</code>
       *
       * <pre>
       *¿¨1
       * </pre>
       */
      public Builder setCard1(int value) {
        bitField0_ |= 0x00000002;
        card1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card1 = 2;</code>
       *
       * <pre>
       *¿¨1
       * </pre>
       */
      public Builder clearCard1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        card1_ = 0;
        onChanged();
        return this;
      }

      private int card2_ ;
      /**
       * <code>optional int32 card2 = 3;</code>
       *
       * <pre>
       *¿¨2
       * </pre>
       */
      public boolean hasCard2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 card2 = 3;</code>
       *
       * <pre>
       *¿¨2
       * </pre>
       */
      public int getCard2() {
        return card2_;
      }
      /**
       * <code>optional int32 card2 = 3;</code>
       *
       * <pre>
       *¿¨2
       * </pre>
       */
      public Builder setCard2(int value) {
        bitField0_ |= 0x00000004;
        card2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card2 = 3;</code>
       *
       * <pre>
       *¿¨2
       * </pre>
       */
      public Builder clearCard2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        card2_ = 0;
        onChanged();
        return this;
      }

      private int card3_ ;
      /**
       * <code>optional int32 card3 = 4;</code>
       *
       * <pre>
       *¿¨3
       * </pre>
       */
      public boolean hasCard3() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 card3 = 4;</code>
       *
       * <pre>
       *¿¨3
       * </pre>
       */
      public int getCard3() {
        return card3_;
      }
      /**
       * <code>optional int32 card3 = 4;</code>
       *
       * <pre>
       *¿¨3
       * </pre>
       */
      public Builder setCard3(int value) {
        bitField0_ |= 0x00000008;
        card3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card3 = 4;</code>
       *
       * <pre>
       *¿¨3
       * </pre>
       */
      public Builder clearCard3() {
        bitField0_ = (bitField0_ & ~0x00000008);
        card3_ = 0;
        onChanged();
        return this;
      }

      private int card4_ ;
      /**
       * <code>optional int32 card4 = 5;</code>
       *
       * <pre>
       *¿¨4
       * </pre>
       */
      public boolean hasCard4() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 card4 = 5;</code>
       *
       * <pre>
       *¿¨4
       * </pre>
       */
      public int getCard4() {
        return card4_;
      }
      /**
       * <code>optional int32 card4 = 5;</code>
       *
       * <pre>
       *¿¨4
       * </pre>
       */
      public Builder setCard4(int value) {
        bitField0_ |= 0x00000010;
        card4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card4 = 5;</code>
       *
       * <pre>
       *¿¨4
       * </pre>
       */
      public Builder clearCard4() {
        bitField0_ = (bitField0_ & ~0x00000010);
        card4_ = 0;
        onChanged();
        return this;
      }

      private int card5_ ;
      /**
       * <code>optional int32 card5 = 6;</code>
       *
       * <pre>
       *¿¨5
       * </pre>
       */
      public boolean hasCard5() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 card5 = 6;</code>
       *
       * <pre>
       *¿¨5
       * </pre>
       */
      public int getCard5() {
        return card5_;
      }
      /**
       * <code>optional int32 card5 = 6;</code>
       *
       * <pre>
       *¿¨5
       * </pre>
       */
      public Builder setCard5(int value) {
        bitField0_ |= 0x00000020;
        card5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card5 = 6;</code>
       *
       * <pre>
       *¿¨5
       * </pre>
       */
      public Builder clearCard5() {
        bitField0_ = (bitField0_ & ~0x00000020);
        card5_ = 0;
        onChanged();
        return this;
      }

      private int card6_ ;
      /**
       * <code>optional int32 card6 = 7;</code>
       *
       * <pre>
       *¿¨6
       * </pre>
       */
      public boolean hasCard6() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 card6 = 7;</code>
       *
       * <pre>
       *¿¨6
       * </pre>
       */
      public int getCard6() {
        return card6_;
      }
      /**
       * <code>optional int32 card6 = 7;</code>
       *
       * <pre>
       *¿¨6
       * </pre>
       */
      public Builder setCard6(int value) {
        bitField0_ |= 0x00000040;
        card6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card6 = 7;</code>
       *
       * <pre>
       *¿¨6
       * </pre>
       */
      public Builder clearCard6() {
        bitField0_ = (bitField0_ & ~0x00000040);
        card6_ = 0;
        onChanged();
        return this;
      }

      private int card7_ ;
      /**
       * <code>optional int32 card7 = 8;</code>
       *
       * <pre>
       *¿¨7
       * </pre>
       */
      public boolean hasCard7() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 card7 = 8;</code>
       *
       * <pre>
       *¿¨7
       * </pre>
       */
      public int getCard7() {
        return card7_;
      }
      /**
       * <code>optional int32 card7 = 8;</code>
       *
       * <pre>
       *¿¨7
       * </pre>
       */
      public Builder setCard7(int value) {
        bitField0_ |= 0x00000080;
        card7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card7 = 8;</code>
       *
       * <pre>
       *¿¨7
       * </pre>
       */
      public Builder clearCard7() {
        bitField0_ = (bitField0_ & ~0x00000080);
        card7_ = 0;
        onChanged();
        return this;
      }

      private int card8_ ;
      /**
       * <code>optional int32 card8 = 9;</code>
       *
       * <pre>
       *¿¨8
       * </pre>
       */
      public boolean hasCard8() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 card8 = 9;</code>
       *
       * <pre>
       *¿¨8
       * </pre>
       */
      public int getCard8() {
        return card8_;
      }
      /**
       * <code>optional int32 card8 = 9;</code>
       *
       * <pre>
       *¿¨8
       * </pre>
       */
      public Builder setCard8(int value) {
        bitField0_ |= 0x00000100;
        card8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card8 = 9;</code>
       *
       * <pre>
       *¿¨8
       * </pre>
       */
      public Builder clearCard8() {
        bitField0_ = (bitField0_ & ~0x00000100);
        card8_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> cardInfos_ =
        java.util.Collections.emptyList();
      private void ensureCardInfosIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          cardInfos_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg>(cardInfos_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder> cardInfosBuilder_;

      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> getCardInfosList() {
        if (cardInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cardInfos_);
        } else {
          return cardInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public int getCardInfosCount() {
        if (cardInfosBuilder_ == null) {
          return cardInfos_.size();
        } else {
          return cardInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg getCardInfos(int index) {
        if (cardInfosBuilder_ == null) {
          return cardInfos_.get(index);
        } else {
          return cardInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder setCardInfos(
          int index, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg value) {
        if (cardInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardInfosIsMutable();
          cardInfos_.set(index, value);
          onChanged();
        } else {
          cardInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder setCardInfos(
          int index, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder builderForValue) {
        if (cardInfosBuilder_ == null) {
          ensureCardInfosIsMutable();
          cardInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder addCardInfos(com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg value) {
        if (cardInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardInfosIsMutable();
          cardInfos_.add(value);
          onChanged();
        } else {
          cardInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder addCardInfos(
          int index, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg value) {
        if (cardInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardInfosIsMutable();
          cardInfos_.add(index, value);
          onChanged();
        } else {
          cardInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder addCardInfos(
          com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder builderForValue) {
        if (cardInfosBuilder_ == null) {
          ensureCardInfosIsMutable();
          cardInfos_.add(builderForValue.build());
          onChanged();
        } else {
          cardInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder addCardInfos(
          int index, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder builderForValue) {
        if (cardInfosBuilder_ == null) {
          ensureCardInfosIsMutable();
          cardInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder addAllCardInfos(
          java.lang.Iterable<? extends com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg> values) {
        if (cardInfosBuilder_ == null) {
          ensureCardInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cardInfos_);
          onChanged();
        } else {
          cardInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder clearCardInfos() {
        if (cardInfosBuilder_ == null) {
          cardInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          cardInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public Builder removeCardInfos(int index) {
        if (cardInfosBuilder_ == null) {
          ensureCardInfosIsMutable();
          cardInfos_.remove(index);
          onChanged();
        } else {
          cardInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder getCardInfosBuilder(
          int index) {
        return getCardInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder getCardInfosOrBuilder(
          int index) {
        if (cardInfosBuilder_ == null) {
          return cardInfos_.get(index);  } else {
          return cardInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public java.util.List<? extends com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder> 
           getCardInfosOrBuilderList() {
        if (cardInfosBuilder_ != null) {
          return cardInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cardInfos_);
        }
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder addCardInfosBuilder() {
        return getCardInfosFieldBuilder().addBuilder(
            com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder addCardInfosBuilder(
          int index) {
        return getCardInfosFieldBuilder().addBuilder(
            index, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .CardInfoMsg cardInfos = 10;</code>
       *
       * <pre>
       *»êá¦ÏêÏ¸ÐÅÏ¢
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder> 
           getCardInfosBuilderList() {
        return getCardInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder> 
          getCardInfosFieldBuilder() {
        if (cardInfosBuilder_ == null) {
          cardInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsg.Builder, com.chuangyou.common.protobuf.pb.soul.CardInfoProto.CardInfoMsgOrBuilder>(
                  cardInfos_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          cardInfos_ = null;
        }
        return cardInfosBuilder_;
      }

      private com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg propertitys_ = com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder> propertitysBuilder_;
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public boolean hasPropertitys() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg getPropertitys() {
        if (propertitysBuilder_ == null) {
          return propertitys_;
        } else {
          return propertitysBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public Builder setPropertitys(com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg value) {
        if (propertitysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          propertitys_ = value;
          onChanged();
        } else {
          propertitysBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public Builder setPropertitys(
          com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder builderForValue) {
        if (propertitysBuilder_ == null) {
          propertitys_ = builderForValue.build();
          onChanged();
        } else {
          propertitysBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public Builder mergePropertitys(com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg value) {
        if (propertitysBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              propertitys_ != com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.getDefaultInstance()) {
            propertitys_ =
              com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.newBuilder(propertitys_).mergeFrom(value).buildPartial();
          } else {
            propertitys_ = value;
          }
          onChanged();
        } else {
          propertitysBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public Builder clearPropertitys() {
        if (propertitysBuilder_ == null) {
          propertitys_ = com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.getDefaultInstance();
          onChanged();
        } else {
          propertitysBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder getPropertitysBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getPropertitysFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder getPropertitysOrBuilder() {
        if (propertitysBuilder_ != null) {
          return propertitysBuilder_.getMessageOrBuilder();
        } else {
          return propertitys_;
        }
      }
      /**
       * <code>optional .PropertyListMsg propertitys = 11;</code>
       *
       * <pre>
       *»êá¦ÊôÐÔÁÐ±í
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder> 
          getPropertitysFieldBuilder() {
        if (propertitysBuilder_ == null) {
          propertitysBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsg.Builder, com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.PropertyListMsgOrBuilder>(
                  getPropertitys(),
                  getParentForChildren(),
                  isClean());
          propertitys_ = null;
        }
        return propertitysBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OtherSoulMsg)
    }

    static {
      defaultInstance = new OtherSoulMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OtherSoulMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OtherSoulMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OtherSoulMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OtherSoulMsg.proto\032\025PropertyListMsg.pr" +
      "oto\032\021CardInfoMsg.proto\"\340\001\n\014OtherSoulMsg\022" +
      "\020\n\010playerId\030\001 \001(\003\022\r\n\005card1\030\002 \001(\005\022\r\n\005card" +
      "2\030\003 \001(\005\022\r\n\005card3\030\004 \001(\005\022\r\n\005card4\030\005 \001(\005\022\r\n" +
      "\005card5\030\006 \001(\005\022\r\n\005card6\030\007 \001(\005\022\r\n\005card7\030\010 \001" +
      "(\005\022\r\n\005card8\030\t \001(\005\022\037\n\tcardInfos\030\n \003(\0132\014.C" +
      "ardInfoMsg\022%\n\013propertitys\030\013 \001(\0132\020.Proper" +
      "tyListMsgB:\n\'com.chuangyou.common.protob" +
      "uf.pb.playerB\017OtherSoulgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.getDescriptor(),
          com.chuangyou.common.protobuf.pb.soul.CardInfoProto.getDescriptor(),
        }, assigner);
    internal_static_OtherSoulMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OtherSoulMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OtherSoulMsg_descriptor,
        new java.lang.String[] { "PlayerId", "Card1", "Card2", "Card3", "Card4", "Card5", "Card6", "Card7", "Card8", "CardInfos", "Propertitys", });
    com.chuangyou.common.protobuf.pb.army.PropertyListMsgProto.getDescriptor();
    com.chuangyou.common.protobuf.pb.soul.CardInfoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
