// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npcShop/NpcShopBuyGoodRespMsg.proto

package com.chuangyou.common.protobuf.pb.npcShop;

public final class NpcShopBuyGoodRespProto {
  private NpcShopBuyGoodRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NpcShopBuyGoodRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NpcShopBuyGoodRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 privateId = 1;</code>
     *
     * <pre>
     *商品配置表中的唯一ID
     * </pre>
     */
    boolean hasPrivateId();
    /**
     * <code>required int32 privateId = 1;</code>
     *
     * <pre>
     *商品配置表中的唯一ID
     * </pre>
     */
    int getPrivateId();

    /**
     * <code>required int32 serverProcured = 2;</code>
     *
     * <pre>
     *全服已购数量， 等于-1时代表无限出售
     * </pre>
     */
    boolean hasServerProcured();
    /**
     * <code>required int32 serverProcured = 2;</code>
     *
     * <pre>
     *全服已购数量， 等于-1时代表无限出售
     * </pre>
     */
    int getServerProcured();

    /**
     * <code>required int32 roleProcured = 3;</code>
     *
     * <pre>
     *单个用户已购数量，等于-1时代表不限购
     * </pre>
     */
    boolean hasRoleProcured();
    /**
     * <code>required int32 roleProcured = 3;</code>
     *
     * <pre>
     *单个用户已购数量，等于-1时代表不限购
     * </pre>
     */
    int getRoleProcured();
  }
  /**
   * Protobuf type {@code NpcShopBuyGoodRespMsg}
   *
   * <pre>
   *购买商品
   *成功返回（失败会返回相关错误码）
   * </pre>
   */
  public static final class NpcShopBuyGoodRespMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NpcShopBuyGoodRespMsg)
      NpcShopBuyGoodRespMsgOrBuilder {
    // Use NpcShopBuyGoodRespMsg.newBuilder() to construct.
    private NpcShopBuyGoodRespMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NpcShopBuyGoodRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NpcShopBuyGoodRespMsg defaultInstance;
    public static NpcShopBuyGoodRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public NpcShopBuyGoodRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NpcShopBuyGoodRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              privateId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverProcured_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roleProcured_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.internal_static_NpcShopBuyGoodRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.internal_static_NpcShopBuyGoodRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.class, com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<NpcShopBuyGoodRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<NpcShopBuyGoodRespMsg>() {
      public NpcShopBuyGoodRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NpcShopBuyGoodRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NpcShopBuyGoodRespMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PRIVATEID_FIELD_NUMBER = 1;
    private int privateId_;
    /**
     * <code>required int32 privateId = 1;</code>
     *
     * <pre>
     *商品配置表中的唯一ID
     * </pre>
     */
    public boolean hasPrivateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 privateId = 1;</code>
     *
     * <pre>
     *商品配置表中的唯一ID
     * </pre>
     */
    public int getPrivateId() {
      return privateId_;
    }

    public static final int SERVERPROCURED_FIELD_NUMBER = 2;
    private int serverProcured_;
    /**
     * <code>required int32 serverProcured = 2;</code>
     *
     * <pre>
     *全服已购数量， 等于-1时代表无限出售
     * </pre>
     */
    public boolean hasServerProcured() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverProcured = 2;</code>
     *
     * <pre>
     *全服已购数量， 等于-1时代表无限出售
     * </pre>
     */
    public int getServerProcured() {
      return serverProcured_;
    }

    public static final int ROLEPROCURED_FIELD_NUMBER = 3;
    private int roleProcured_;
    /**
     * <code>required int32 roleProcured = 3;</code>
     *
     * <pre>
     *单个用户已购数量，等于-1时代表不限购
     * </pre>
     */
    public boolean hasRoleProcured() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 roleProcured = 3;</code>
     *
     * <pre>
     *单个用户已购数量，等于-1时代表不限购
     * </pre>
     */
    public int getRoleProcured() {
      return roleProcured_;
    }

    private void initFields() {
      privateId_ = 0;
      serverProcured_ = 0;
      roleProcured_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPrivateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerProcured()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleProcured()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, privateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverProcured_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, roleProcured_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, privateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverProcured_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roleProcured_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NpcShopBuyGoodRespMsg}
     *
     * <pre>
     *购买商品
     *成功返回（失败会返回相关错误码）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NpcShopBuyGoodRespMsg)
        com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.internal_static_NpcShopBuyGoodRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.internal_static_NpcShopBuyGoodRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.class, com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        privateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverProcured_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        roleProcured_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.internal_static_NpcShopBuyGoodRespMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg build() {
        com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg result = new com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.privateId_ = privateId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverProcured_ = serverProcured_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roleProcured_ = roleProcured_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg.getDefaultInstance()) return this;
        if (other.hasPrivateId()) {
          setPrivateId(other.getPrivateId());
        }
        if (other.hasServerProcured()) {
          setServerProcured(other.getServerProcured());
        }
        if (other.hasRoleProcured()) {
          setRoleProcured(other.getRoleProcured());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrivateId()) {
          
          return false;
        }
        if (!hasServerProcured()) {
          
          return false;
        }
        if (!hasRoleProcured()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.npcShop.NpcShopBuyGoodRespProto.NpcShopBuyGoodRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int privateId_ ;
      /**
       * <code>required int32 privateId = 1;</code>
       *
       * <pre>
       *商品配置表中的唯一ID
       * </pre>
       */
      public boolean hasPrivateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 privateId = 1;</code>
       *
       * <pre>
       *商品配置表中的唯一ID
       * </pre>
       */
      public int getPrivateId() {
        return privateId_;
      }
      /**
       * <code>required int32 privateId = 1;</code>
       *
       * <pre>
       *商品配置表中的唯一ID
       * </pre>
       */
      public Builder setPrivateId(int value) {
        bitField0_ |= 0x00000001;
        privateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 privateId = 1;</code>
       *
       * <pre>
       *商品配置表中的唯一ID
       * </pre>
       */
      public Builder clearPrivateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        privateId_ = 0;
        onChanged();
        return this;
      }

      private int serverProcured_ ;
      /**
       * <code>required int32 serverProcured = 2;</code>
       *
       * <pre>
       *全服已购数量， 等于-1时代表无限出售
       * </pre>
       */
      public boolean hasServerProcured() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverProcured = 2;</code>
       *
       * <pre>
       *全服已购数量， 等于-1时代表无限出售
       * </pre>
       */
      public int getServerProcured() {
        return serverProcured_;
      }
      /**
       * <code>required int32 serverProcured = 2;</code>
       *
       * <pre>
       *全服已购数量， 等于-1时代表无限出售
       * </pre>
       */
      public Builder setServerProcured(int value) {
        bitField0_ |= 0x00000002;
        serverProcured_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverProcured = 2;</code>
       *
       * <pre>
       *全服已购数量， 等于-1时代表无限出售
       * </pre>
       */
      public Builder clearServerProcured() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverProcured_ = 0;
        onChanged();
        return this;
      }

      private int roleProcured_ ;
      /**
       * <code>required int32 roleProcured = 3;</code>
       *
       * <pre>
       *单个用户已购数量，等于-1时代表不限购
       * </pre>
       */
      public boolean hasRoleProcured() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 roleProcured = 3;</code>
       *
       * <pre>
       *单个用户已购数量，等于-1时代表不限购
       * </pre>
       */
      public int getRoleProcured() {
        return roleProcured_;
      }
      /**
       * <code>required int32 roleProcured = 3;</code>
       *
       * <pre>
       *单个用户已购数量，等于-1时代表不限购
       * </pre>
       */
      public Builder setRoleProcured(int value) {
        bitField0_ |= 0x00000004;
        roleProcured_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roleProcured = 3;</code>
       *
       * <pre>
       *单个用户已购数量，等于-1时代表不限购
       * </pre>
       */
      public Builder clearRoleProcured() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleProcured_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NpcShopBuyGoodRespMsg)
    }

    static {
      defaultInstance = new NpcShopBuyGoodRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NpcShopBuyGoodRespMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NpcShopBuyGoodRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NpcShopBuyGoodRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#npcShop/NpcShopBuyGoodRespMsg.proto\"X\n" +
      "\025NpcShopBuyGoodRespMsg\022\021\n\tprivateId\030\001 \002(" +
      "\005\022\026\n\016serverProcured\030\002 \002(\005\022\024\n\014roleProcure" +
      "d\030\003 \002(\005BC\n(com.chuangyou.common.protobuf" +
      ".pb.npcShopB\027NpcShopBuyGoodRespProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NpcShopBuyGoodRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NpcShopBuyGoodRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NpcShopBuyGoodRespMsg_descriptor,
        new java.lang.String[] { "PrivateId", "ServerProcured", "RoleProcured", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
