// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: magicwp/MagicwpRefineGetInfoRespMsg.proto

package com.chuangyou.common.protobuf.pb.magicwp;

public final class MagicwpRefineGetInfoRespProto {
  private MagicwpRefineGetInfoRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MagicwpRefineGetInfoRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MagicwpRefineGetInfoRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 magicwpId = 1;</code>
     *
     * <pre>
     * 法宝ID
     * </pre>
     */
    boolean hasMagicwpId();
    /**
     * <code>optional int32 magicwpId = 1;</code>
     *
     * <pre>
     * 法宝ID
     * </pre>
     */
    int getMagicwpId();

    /**
     * <code>optional int32 grade = 2;</code>
     *
     * <pre>
     * 法宝进阶等级(0未激活)
     * </pre>
     */
    boolean hasGrade();
    /**
     * <code>optional int32 grade = 2;</code>
     *
     * <pre>
     * 法宝进阶等级(0未激活)
     * </pre>
     */
    int getGrade();

    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> 
        getAttListList();
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getAttList(int index);
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    int getAttListCount();
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
        getAttListOrBuilderList();
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getAttListOrBuilder(
        int index);

    /**
     * <code>optional int32 hasUnSaveAtt = 4;</code>
     *
     * <pre>
     * 是否有未保存的洗炼属性
     * </pre>
     */
    boolean hasHasUnSaveAtt();
    /**
     * <code>optional int32 hasUnSaveAtt = 4;</code>
     *
     * <pre>
     * 是否有未保存的洗炼属性
     * </pre>
     */
    int getHasUnSaveAtt();

    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> 
        getTmpListList();
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getTmpList(int index);
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    int getTmpListCount();
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
        getTmpListOrBuilderList();
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getTmpListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MagicwpRefineGetInfoRespMsg}
   */
  public static final class MagicwpRefineGetInfoRespMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MagicwpRefineGetInfoRespMsg)
      MagicwpRefineGetInfoRespMsgOrBuilder {
    // Use MagicwpRefineGetInfoRespMsg.newBuilder() to construct.
    private MagicwpRefineGetInfoRespMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MagicwpRefineGetInfoRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MagicwpRefineGetInfoRespMsg defaultInstance;
    public static MagicwpRefineGetInfoRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MagicwpRefineGetInfoRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MagicwpRefineGetInfoRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              magicwpId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              grade_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                attList_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg>();
                mutable_bitField0_ |= 0x00000004;
              }
              attList_.add(input.readMessage(com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              hasUnSaveAtt_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                tmpList_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg>();
                mutable_bitField0_ |= 0x00000010;
              }
              tmpList_.add(input.readMessage(com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          attList_ = java.util.Collections.unmodifiableList(attList_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          tmpList_ = java.util.Collections.unmodifiableList(tmpList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.internal_static_MagicwpRefineGetInfoRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.internal_static_MagicwpRefineGetInfoRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.class, com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MagicwpRefineGetInfoRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<MagicwpRefineGetInfoRespMsg>() {
      public MagicwpRefineGetInfoRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MagicwpRefineGetInfoRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MagicwpRefineGetInfoRespMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MAGICWPID_FIELD_NUMBER = 1;
    private int magicwpId_;
    /**
     * <code>optional int32 magicwpId = 1;</code>
     *
     * <pre>
     * 法宝ID
     * </pre>
     */
    public boolean hasMagicwpId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 magicwpId = 1;</code>
     *
     * <pre>
     * 法宝ID
     * </pre>
     */
    public int getMagicwpId() {
      return magicwpId_;
    }

    public static final int GRADE_FIELD_NUMBER = 2;
    private int grade_;
    /**
     * <code>optional int32 grade = 2;</code>
     *
     * <pre>
     * 法宝进阶等级(0未激活)
     * </pre>
     */
    public boolean hasGrade() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 grade = 2;</code>
     *
     * <pre>
     * 法宝进阶等级(0未激活)
     * </pre>
     */
    public int getGrade() {
      return grade_;
    }

    public static final int ATTLIST_FIELD_NUMBER = 3;
    private java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> attList_;
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> getAttListList() {
      return attList_;
    }
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    public java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
        getAttListOrBuilderList() {
      return attList_;
    }
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    public int getAttListCount() {
      return attList_.size();
    }
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getAttList(int index) {
      return attList_.get(index);
    }
    /**
     * <code>repeated .AttributeBeanMsg attList = 3;</code>
     *
     * <pre>
     * 法宝当前洗炼出的总属性列表
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getAttListOrBuilder(
        int index) {
      return attList_.get(index);
    }

    public static final int HASUNSAVEATT_FIELD_NUMBER = 4;
    private int hasUnSaveAtt_;
    /**
     * <code>optional int32 hasUnSaveAtt = 4;</code>
     *
     * <pre>
     * 是否有未保存的洗炼属性
     * </pre>
     */
    public boolean hasHasUnSaveAtt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 hasUnSaveAtt = 4;</code>
     *
     * <pre>
     * 是否有未保存的洗炼属性
     * </pre>
     */
    public int getHasUnSaveAtt() {
      return hasUnSaveAtt_;
    }

    public static final int TMPLIST_FIELD_NUMBER = 5;
    private java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> tmpList_;
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> getTmpListList() {
      return tmpList_;
    }
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    public java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
        getTmpListOrBuilderList() {
      return tmpList_;
    }
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    public int getTmpListCount() {
      return tmpList_.size();
    }
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getTmpList(int index) {
      return tmpList_.get(index);
    }
    /**
     * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
     *
     * <pre>
     * 洗炼后未保存的临时洗炼属性
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getTmpListOrBuilder(
        int index) {
      return tmpList_.get(index);
    }

    private void initFields() {
      magicwpId_ = 0;
      grade_ = 0;
      attList_ = java.util.Collections.emptyList();
      hasUnSaveAtt_ = 0;
      tmpList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, magicwpId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, grade_);
      }
      for (int i = 0; i < attList_.size(); i++) {
        output.writeMessage(3, attList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, hasUnSaveAtt_);
      }
      for (int i = 0; i < tmpList_.size(); i++) {
        output.writeMessage(5, tmpList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, magicwpId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, grade_);
      }
      for (int i = 0; i < attList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, attList_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hasUnSaveAtt_);
      }
      for (int i = 0; i < tmpList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, tmpList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MagicwpRefineGetInfoRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MagicwpRefineGetInfoRespMsg)
        com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.internal_static_MagicwpRefineGetInfoRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.internal_static_MagicwpRefineGetInfoRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.class, com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttListFieldBuilder();
          getTmpListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        magicwpId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        grade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (attListBuilder_ == null) {
          attList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          attListBuilder_.clear();
        }
        hasUnSaveAtt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (tmpListBuilder_ == null) {
          tmpList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          tmpListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.internal_static_MagicwpRefineGetInfoRespMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg build() {
        com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg result = new com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.magicwpId_ = magicwpId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.grade_ = grade_;
        if (attListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            attList_ = java.util.Collections.unmodifiableList(attList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.attList_ = attList_;
        } else {
          result.attList_ = attListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hasUnSaveAtt_ = hasUnSaveAtt_;
        if (tmpListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            tmpList_ = java.util.Collections.unmodifiableList(tmpList_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.tmpList_ = tmpList_;
        } else {
          result.tmpList_ = tmpListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg.getDefaultInstance()) return this;
        if (other.hasMagicwpId()) {
          setMagicwpId(other.getMagicwpId());
        }
        if (other.hasGrade()) {
          setGrade(other.getGrade());
        }
        if (attListBuilder_ == null) {
          if (!other.attList_.isEmpty()) {
            if (attList_.isEmpty()) {
              attList_ = other.attList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAttListIsMutable();
              attList_.addAll(other.attList_);
            }
            onChanged();
          }
        } else {
          if (!other.attList_.isEmpty()) {
            if (attListBuilder_.isEmpty()) {
              attListBuilder_.dispose();
              attListBuilder_ = null;
              attList_ = other.attList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              attListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttListFieldBuilder() : null;
            } else {
              attListBuilder_.addAllMessages(other.attList_);
            }
          }
        }
        if (other.hasHasUnSaveAtt()) {
          setHasUnSaveAtt(other.getHasUnSaveAtt());
        }
        if (tmpListBuilder_ == null) {
          if (!other.tmpList_.isEmpty()) {
            if (tmpList_.isEmpty()) {
              tmpList_ = other.tmpList_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureTmpListIsMutable();
              tmpList_.addAll(other.tmpList_);
            }
            onChanged();
          }
        } else {
          if (!other.tmpList_.isEmpty()) {
            if (tmpListBuilder_.isEmpty()) {
              tmpListBuilder_.dispose();
              tmpListBuilder_ = null;
              tmpList_ = other.tmpList_;
              bitField0_ = (bitField0_ & ~0x00000010);
              tmpListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTmpListFieldBuilder() : null;
            } else {
              tmpListBuilder_.addAllMessages(other.tmpList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.magicwp.MagicwpRefineGetInfoRespProto.MagicwpRefineGetInfoRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int magicwpId_ ;
      /**
       * <code>optional int32 magicwpId = 1;</code>
       *
       * <pre>
       * 法宝ID
       * </pre>
       */
      public boolean hasMagicwpId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 magicwpId = 1;</code>
       *
       * <pre>
       * 法宝ID
       * </pre>
       */
      public int getMagicwpId() {
        return magicwpId_;
      }
      /**
       * <code>optional int32 magicwpId = 1;</code>
       *
       * <pre>
       * 法宝ID
       * </pre>
       */
      public Builder setMagicwpId(int value) {
        bitField0_ |= 0x00000001;
        magicwpId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 magicwpId = 1;</code>
       *
       * <pre>
       * 法宝ID
       * </pre>
       */
      public Builder clearMagicwpId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        magicwpId_ = 0;
        onChanged();
        return this;
      }

      private int grade_ ;
      /**
       * <code>optional int32 grade = 2;</code>
       *
       * <pre>
       * 法宝进阶等级(0未激活)
       * </pre>
       */
      public boolean hasGrade() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 grade = 2;</code>
       *
       * <pre>
       * 法宝进阶等级(0未激活)
       * </pre>
       */
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>optional int32 grade = 2;</code>
       *
       * <pre>
       * 法宝进阶等级(0未激活)
       * </pre>
       */
      public Builder setGrade(int value) {
        bitField0_ |= 0x00000002;
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 grade = 2;</code>
       *
       * <pre>
       * 法宝进阶等级(0未激活)
       * </pre>
       */
      public Builder clearGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        grade_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> attList_ =
        java.util.Collections.emptyList();
      private void ensureAttListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          attList_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg>(attList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> attListBuilder_;

      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> getAttListList() {
        if (attListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attList_);
        } else {
          return attListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public int getAttListCount() {
        if (attListBuilder_ == null) {
          return attList_.size();
        } else {
          return attListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getAttList(int index) {
        if (attListBuilder_ == null) {
          return attList_.get(index);
        } else {
          return attListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder setAttList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (attListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttListIsMutable();
          attList_.set(index, value);
          onChanged();
        } else {
          attListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder setAttList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (attListBuilder_ == null) {
          ensureAttListIsMutable();
          attList_.set(index, builderForValue.build());
          onChanged();
        } else {
          attListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder addAttList(com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (attListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttListIsMutable();
          attList_.add(value);
          onChanged();
        } else {
          attListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder addAttList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (attListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttListIsMutable();
          attList_.add(index, value);
          onChanged();
        } else {
          attListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder addAttList(
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (attListBuilder_ == null) {
          ensureAttListIsMutable();
          attList_.add(builderForValue.build());
          onChanged();
        } else {
          attListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder addAttList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (attListBuilder_ == null) {
          ensureAttListIsMutable();
          attList_.add(index, builderForValue.build());
          onChanged();
        } else {
          attListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder addAllAttList(
          java.lang.Iterable<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> values) {
        if (attListBuilder_ == null) {
          ensureAttListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attList_);
          onChanged();
        } else {
          attListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder clearAttList() {
        if (attListBuilder_ == null) {
          attList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          attListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public Builder removeAttList(int index) {
        if (attListBuilder_ == null) {
          ensureAttListIsMutable();
          attList_.remove(index);
          onChanged();
        } else {
          attListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder getAttListBuilder(
          int index) {
        return getAttListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getAttListOrBuilder(
          int index) {
        if (attListBuilder_ == null) {
          return attList_.get(index);  } else {
          return attListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
           getAttListOrBuilderList() {
        if (attListBuilder_ != null) {
          return attListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attList_);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder addAttListBuilder() {
        return getAttListFieldBuilder().addBuilder(
            com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder addAttListBuilder(
          int index) {
        return getAttListFieldBuilder().addBuilder(
            index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeBeanMsg attList = 3;</code>
       *
       * <pre>
       * 法宝当前洗炼出的总属性列表
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder> 
           getAttListBuilderList() {
        return getAttListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
          getAttListFieldBuilder() {
        if (attListBuilder_ == null) {
          attListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder>(
                  attList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          attList_ = null;
        }
        return attListBuilder_;
      }

      private int hasUnSaveAtt_ ;
      /**
       * <code>optional int32 hasUnSaveAtt = 4;</code>
       *
       * <pre>
       * 是否有未保存的洗炼属性
       * </pre>
       */
      public boolean hasHasUnSaveAtt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 hasUnSaveAtt = 4;</code>
       *
       * <pre>
       * 是否有未保存的洗炼属性
       * </pre>
       */
      public int getHasUnSaveAtt() {
        return hasUnSaveAtt_;
      }
      /**
       * <code>optional int32 hasUnSaveAtt = 4;</code>
       *
       * <pre>
       * 是否有未保存的洗炼属性
       * </pre>
       */
      public Builder setHasUnSaveAtt(int value) {
        bitField0_ |= 0x00000008;
        hasUnSaveAtt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hasUnSaveAtt = 4;</code>
       *
       * <pre>
       * 是否有未保存的洗炼属性
       * </pre>
       */
      public Builder clearHasUnSaveAtt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasUnSaveAtt_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> tmpList_ =
        java.util.Collections.emptyList();
      private void ensureTmpListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          tmpList_ = new java.util.ArrayList<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg>(tmpList_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> tmpListBuilder_;

      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> getTmpListList() {
        if (tmpListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tmpList_);
        } else {
          return tmpListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public int getTmpListCount() {
        if (tmpListBuilder_ == null) {
          return tmpList_.size();
        } else {
          return tmpListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg getTmpList(int index) {
        if (tmpListBuilder_ == null) {
          return tmpList_.get(index);
        } else {
          return tmpListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder setTmpList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (tmpListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTmpListIsMutable();
          tmpList_.set(index, value);
          onChanged();
        } else {
          tmpListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder setTmpList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (tmpListBuilder_ == null) {
          ensureTmpListIsMutable();
          tmpList_.set(index, builderForValue.build());
          onChanged();
        } else {
          tmpListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder addTmpList(com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (tmpListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTmpListIsMutable();
          tmpList_.add(value);
          onChanged();
        } else {
          tmpListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder addTmpList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg value) {
        if (tmpListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTmpListIsMutable();
          tmpList_.add(index, value);
          onChanged();
        } else {
          tmpListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder addTmpList(
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (tmpListBuilder_ == null) {
          ensureTmpListIsMutable();
          tmpList_.add(builderForValue.build());
          onChanged();
        } else {
          tmpListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder addTmpList(
          int index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder builderForValue) {
        if (tmpListBuilder_ == null) {
          ensureTmpListIsMutable();
          tmpList_.add(index, builderForValue.build());
          onChanged();
        } else {
          tmpListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder addAllTmpList(
          java.lang.Iterable<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg> values) {
        if (tmpListBuilder_ == null) {
          ensureTmpListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tmpList_);
          onChanged();
        } else {
          tmpListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder clearTmpList() {
        if (tmpListBuilder_ == null) {
          tmpList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          tmpListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public Builder removeTmpList(int index) {
        if (tmpListBuilder_ == null) {
          ensureTmpListIsMutable();
          tmpList_.remove(index);
          onChanged();
        } else {
          tmpListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder getTmpListBuilder(
          int index) {
        return getTmpListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder getTmpListOrBuilder(
          int index) {
        if (tmpListBuilder_ == null) {
          return tmpList_.get(index);  } else {
          return tmpListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public java.util.List<? extends com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
           getTmpListOrBuilderList() {
        if (tmpListBuilder_ != null) {
          return tmpListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tmpList_);
        }
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder addTmpListBuilder() {
        return getTmpListFieldBuilder().addBuilder(
            com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder addTmpListBuilder(
          int index) {
        return getTmpListFieldBuilder().addBuilder(
            index, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .AttributeBeanMsg tmpList = 5;</code>
       *
       * <pre>
       * 洗炼后未保存的临时洗炼属性
       * </pre>
       */
      public java.util.List<com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder> 
           getTmpListBuilderList() {
        return getTmpListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder> 
          getTmpListFieldBuilder() {
        if (tmpListBuilder_ == null) {
          tmpListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsg.Builder, com.chuangyou.common.protobuf.pb.AttributeBeanProto.AttributeBeanMsgOrBuilder>(
                  tmpList_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          tmpList_ = null;
        }
        return tmpListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MagicwpRefineGetInfoRespMsg)
    }

    static {
      defaultInstance = new MagicwpRefineGetInfoRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MagicwpRefineGetInfoRespMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MagicwpRefineGetInfoRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MagicwpRefineGetInfoRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)magicwp/MagicwpRefineGetInfoRespMsg.pr" +
      "oto\032\035common/AttributeBeanMsg.proto\"\235\001\n\033M" +
      "agicwpRefineGetInfoRespMsg\022\021\n\tmagicwpId\030" +
      "\001 \001(\005\022\r\n\005grade\030\002 \001(\005\022\"\n\007attList\030\003 \003(\0132\021." +
      "AttributeBeanMsg\022\024\n\014hasUnSaveAtt\030\004 \001(\005\022\"" +
      "\n\007tmpList\030\005 \003(\0132\021.AttributeBeanMsgBI\n(co" +
      "m.chuangyou.common.protobuf.pb.magicwpB\035" +
      "MagicwpRefineGetInfoRespProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chuangyou.common.protobuf.pb.AttributeBeanProto.getDescriptor(),
        }, assigner);
    internal_static_MagicwpRefineGetInfoRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MagicwpRefineGetInfoRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MagicwpRefineGetInfoRespMsg_descriptor,
        new java.lang.String[] { "MagicwpId", "Grade", "AttList", "HasUnSaveAtt", "TmpList", });
    com.chuangyou.common.protobuf.pb.AttributeBeanProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
