// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateCampaignByNpcMsg.proto

package com.chuangyou.common.protobuf.pb.campaign;

public final class CreateCampaignByNpcProto {
  private CreateCampaignByNpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreateCampaignByNpcMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreateCampaignByNpcMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    long getPlayerId();

    /**
     * <code>optional int32 campaignId = 2;</code>
     *
     * <pre>
     *副本ID
     * </pre>
     */
    boolean hasCampaignId();
    /**
     * <code>optional int32 campaignId = 2;</code>
     *
     * <pre>
     *副本ID
     * </pre>
     */
    int getCampaignId();

    /**
     * <code>optional int64 npcId = 3;</code>
     *
     * <pre>
     * livingID
     * </pre>
     */
    boolean hasNpcId();
    /**
     * <code>optional int64 npcId = 3;</code>
     *
     * <pre>
     * livingID
     * </pre>
     */
    long getNpcId();
  }
  /**
   * Protobuf type {@code CreateCampaignByNpcMsg}
   *
   * <pre>
   *根据NPC创建副本
   * </pre>
   */
  public static final class CreateCampaignByNpcMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CreateCampaignByNpcMsg)
      CreateCampaignByNpcMsgOrBuilder {
    // Use CreateCampaignByNpcMsg.newBuilder() to construct.
    private CreateCampaignByNpcMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateCampaignByNpcMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateCampaignByNpcMsg defaultInstance;
    public static CreateCampaignByNpcMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CreateCampaignByNpcMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateCampaignByNpcMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              campaignId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              npcId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.internal_static_CreateCampaignByNpcMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.internal_static_CreateCampaignByNpcMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.class, com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateCampaignByNpcMsg> PARSER =
        new com.google.protobuf.AbstractParser<CreateCampaignByNpcMsg>() {
      public CreateCampaignByNpcMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateCampaignByNpcMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateCampaignByNpcMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int CAMPAIGNID_FIELD_NUMBER = 2;
    private int campaignId_;
    /**
     * <code>optional int32 campaignId = 2;</code>
     *
     * <pre>
     *副本ID
     * </pre>
     */
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 campaignId = 2;</code>
     *
     * <pre>
     *副本ID
     * </pre>
     */
    public int getCampaignId() {
      return campaignId_;
    }

    public static final int NPCID_FIELD_NUMBER = 3;
    private long npcId_;
    /**
     * <code>optional int64 npcId = 3;</code>
     *
     * <pre>
     * livingID
     * </pre>
     */
    public boolean hasNpcId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 npcId = 3;</code>
     *
     * <pre>
     * livingID
     * </pre>
     */
    public long getNpcId() {
      return npcId_;
    }

    private void initFields() {
      playerId_ = 0L;
      campaignId_ = 0;
      npcId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, campaignId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, npcId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, campaignId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, npcId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreateCampaignByNpcMsg}
     *
     * <pre>
     *根据NPC创建副本
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreateCampaignByNpcMsg)
        com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.internal_static_CreateCampaignByNpcMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.internal_static_CreateCampaignByNpcMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.class, com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        campaignId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        npcId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.internal_static_CreateCampaignByNpcMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg build() {
        com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg result = new com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.campaignId_ = campaignId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.npcId_ = npcId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasCampaignId()) {
          setCampaignId(other.getCampaignId());
        }
        if (other.hasNpcId()) {
          setNpcId(other.getNpcId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.campaign.CreateCampaignByNpcProto.CreateCampaignByNpcMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int campaignId_ ;
      /**
       * <code>optional int32 campaignId = 2;</code>
       *
       * <pre>
       *副本ID
       * </pre>
       */
      public boolean hasCampaignId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 campaignId = 2;</code>
       *
       * <pre>
       *副本ID
       * </pre>
       */
      public int getCampaignId() {
        return campaignId_;
      }
      /**
       * <code>optional int32 campaignId = 2;</code>
       *
       * <pre>
       *副本ID
       * </pre>
       */
      public Builder setCampaignId(int value) {
        bitField0_ |= 0x00000002;
        campaignId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 campaignId = 2;</code>
       *
       * <pre>
       *副本ID
       * </pre>
       */
      public Builder clearCampaignId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        campaignId_ = 0;
        onChanged();
        return this;
      }

      private long npcId_ ;
      /**
       * <code>optional int64 npcId = 3;</code>
       *
       * <pre>
       * livingID
       * </pre>
       */
      public boolean hasNpcId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 npcId = 3;</code>
       *
       * <pre>
       * livingID
       * </pre>
       */
      public long getNpcId() {
        return npcId_;
      }
      /**
       * <code>optional int64 npcId = 3;</code>
       *
       * <pre>
       * livingID
       * </pre>
       */
      public Builder setNpcId(long value) {
        bitField0_ |= 0x00000004;
        npcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 npcId = 3;</code>
       *
       * <pre>
       * livingID
       * </pre>
       */
      public Builder clearNpcId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        npcId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CreateCampaignByNpcMsg)
    }

    static {
      defaultInstance = new CreateCampaignByNpcMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CreateCampaignByNpcMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateCampaignByNpcMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateCampaignByNpcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CreateCampaignByNpcMsg.proto\"M\n\026Create" +
      "CampaignByNpcMsg\022\020\n\010playerId\030\001 \001(\003\022\022\n\nca" +
      "mpaignId\030\002 \001(\005\022\r\n\005npcId\030\003 \001(\003BE\n)com.chu" +
      "angyou.common.protobuf.pb.campaignB\030Crea" +
      "teCampaignByNpcProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CreateCampaignByNpcMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateCampaignByNpcMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateCampaignByNpcMsg_descriptor,
        new java.lang.String[] { "PlayerId", "CampaignId", "NpcId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
