// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soul/SoulInfoMsg.proto

package com.chuangyou.common.protobuf.pb.soul;

public final class SoulInfoProto {
  private SoulInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SoulInfoMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SoulInfoMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *'经验值',
     * </pre>
     */
    boolean hasExp();
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *'经验值',
     * </pre>
     */
    long getExp();

    /**
     * <code>required int32 card1 = 2;</code>
     *
     * <pre>
     * 身上装备的card1--8
     * </pre>
     */
    boolean hasCard1();
    /**
     * <code>required int32 card1 = 2;</code>
     *
     * <pre>
     * 身上装备的card1--8
     * </pre>
     */
    int getCard1();

    /**
     * <code>required int32 card2 = 3;</code>
     */
    boolean hasCard2();
    /**
     * <code>required int32 card2 = 3;</code>
     */
    int getCard2();

    /**
     * <code>required int32 card3 = 4;</code>
     */
    boolean hasCard3();
    /**
     * <code>required int32 card3 = 4;</code>
     */
    int getCard3();

    /**
     * <code>required int32 card4 = 5;</code>
     */
    boolean hasCard4();
    /**
     * <code>required int32 card4 = 5;</code>
     */
    int getCard4();

    /**
     * <code>required int32 card5 = 6;</code>
     */
    boolean hasCard5();
    /**
     * <code>required int32 card5 = 6;</code>
     */
    int getCard5();

    /**
     * <code>required int32 card6 = 7;</code>
     */
    boolean hasCard6();
    /**
     * <code>required int32 card6 = 7;</code>
     */
    int getCard6();

    /**
     * <code>required int32 card7 = 8;</code>
     */
    boolean hasCard7();
    /**
     * <code>required int32 card7 = 8;</code>
     */
    int getCard7();

    /**
     * <code>required int32 card8 = 9;</code>
     */
    boolean hasCard8();
    /**
     * <code>required int32 card8 = 9;</code>
     */
    int getCard8();

    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    boolean hasFuseSkill1();
    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill1();
    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill1OrBuilder();

    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    boolean hasFuseSkill2();
    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill2();
    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill2OrBuilder();

    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    boolean hasFuseSkill3();
    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill3();
    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill3OrBuilder();

    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    boolean hasFuseSkill4();
    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill4();
    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill4OrBuilder();

    /**
     * <code>required int32 proficiency = 14;</code>
     *
     * <pre>
     *制作熟悉度
     * </pre>
     */
    boolean hasProficiency();
    /**
     * <code>required int32 proficiency = 14;</code>
     *
     * <pre>
     *制作熟悉度
     * </pre>
     */
    int getProficiency();
  }
  /**
   * Protobuf type {@code SoulInfoMsg}
   */
  public static final class SoulInfoMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SoulInfoMsg)
      SoulInfoMsgOrBuilder {
    // Use SoulInfoMsg.newBuilder() to construct.
    private SoulInfoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SoulInfoMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SoulInfoMsg defaultInstance;
    public static SoulInfoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SoulInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SoulInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              card1_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              card2_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              card3_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              card4_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              card5_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              card6_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              card7_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              card8_ = input.readInt32();
              break;
            }
            case 82: {
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = fuseSkill1_.toBuilder();
              }
              fuseSkill1_ = input.readMessage(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fuseSkill1_);
                fuseSkill1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 90: {
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = fuseSkill2_.toBuilder();
              }
              fuseSkill2_ = input.readMessage(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fuseSkill2_);
                fuseSkill2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
            case 98: {
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = fuseSkill3_.toBuilder();
              }
              fuseSkill3_ = input.readMessage(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fuseSkill3_);
                fuseSkill3_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
            case 106: {
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00001000) == 0x00001000)) {
                subBuilder = fuseSkill4_.toBuilder();
              }
              fuseSkill4_ = input.readMessage(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fuseSkill4_);
                fuseSkill4_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00001000;
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              proficiency_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.internal_static_SoulInfoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.internal_static_SoulInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.class, com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SoulInfoMsg> PARSER =
        new com.google.protobuf.AbstractParser<SoulInfoMsg>() {
      public SoulInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SoulInfoMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SoulInfoMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EXP_FIELD_NUMBER = 1;
    private long exp_;
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *'经验值',
     * </pre>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *'经验值',
     * </pre>
     */
    public long getExp() {
      return exp_;
    }

    public static final int CARD1_FIELD_NUMBER = 2;
    private int card1_;
    /**
     * <code>required int32 card1 = 2;</code>
     *
     * <pre>
     * 身上装备的card1--8
     * </pre>
     */
    public boolean hasCard1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 card1 = 2;</code>
     *
     * <pre>
     * 身上装备的card1--8
     * </pre>
     */
    public int getCard1() {
      return card1_;
    }

    public static final int CARD2_FIELD_NUMBER = 3;
    private int card2_;
    /**
     * <code>required int32 card2 = 3;</code>
     */
    public boolean hasCard2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 card2 = 3;</code>
     */
    public int getCard2() {
      return card2_;
    }

    public static final int CARD3_FIELD_NUMBER = 4;
    private int card3_;
    /**
     * <code>required int32 card3 = 4;</code>
     */
    public boolean hasCard3() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 card3 = 4;</code>
     */
    public int getCard3() {
      return card3_;
    }

    public static final int CARD4_FIELD_NUMBER = 5;
    private int card4_;
    /**
     * <code>required int32 card4 = 5;</code>
     */
    public boolean hasCard4() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 card4 = 5;</code>
     */
    public int getCard4() {
      return card4_;
    }

    public static final int CARD5_FIELD_NUMBER = 6;
    private int card5_;
    /**
     * <code>required int32 card5 = 6;</code>
     */
    public boolean hasCard5() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 card5 = 6;</code>
     */
    public int getCard5() {
      return card5_;
    }

    public static final int CARD6_FIELD_NUMBER = 7;
    private int card6_;
    /**
     * <code>required int32 card6 = 7;</code>
     */
    public boolean hasCard6() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 card6 = 7;</code>
     */
    public int getCard6() {
      return card6_;
    }

    public static final int CARD7_FIELD_NUMBER = 8;
    private int card7_;
    /**
     * <code>required int32 card7 = 8;</code>
     */
    public boolean hasCard7() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 card7 = 8;</code>
     */
    public int getCard7() {
      return card7_;
    }

    public static final int CARD8_FIELD_NUMBER = 9;
    private int card8_;
    /**
     * <code>required int32 card8 = 9;</code>
     */
    public boolean hasCard8() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 card8 = 9;</code>
     */
    public int getCard8() {
      return card8_;
    }

    public static final int FUSESKILL1_FIELD_NUMBER = 10;
    private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill1_;
    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    public boolean hasFuseSkill1() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill1() {
      return fuseSkill1_;
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
     *
     * <pre>
     *融合技能1--4
     * </pre>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill1OrBuilder() {
      return fuseSkill1_;
    }

    public static final int FUSESKILL2_FIELD_NUMBER = 11;
    private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill2_;
    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    public boolean hasFuseSkill2() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill2() {
      return fuseSkill2_;
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill2OrBuilder() {
      return fuseSkill2_;
    }

    public static final int FUSESKILL3_FIELD_NUMBER = 12;
    private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill3_;
    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    public boolean hasFuseSkill3() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill3() {
      return fuseSkill3_;
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill3OrBuilder() {
      return fuseSkill3_;
    }

    public static final int FUSESKILL4_FIELD_NUMBER = 13;
    private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill4_;
    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    public boolean hasFuseSkill4() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill4() {
      return fuseSkill4_;
    }
    /**
     * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
     */
    public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill4OrBuilder() {
      return fuseSkill4_;
    }

    public static final int PROFICIENCY_FIELD_NUMBER = 14;
    private int proficiency_;
    /**
     * <code>required int32 proficiency = 14;</code>
     *
     * <pre>
     *制作熟悉度
     * </pre>
     */
    public boolean hasProficiency() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int32 proficiency = 14;</code>
     *
     * <pre>
     *制作熟悉度
     * </pre>
     */
    public int getProficiency() {
      return proficiency_;
    }

    private void initFields() {
      exp_ = 0L;
      card1_ = 0;
      card2_ = 0;
      card3_ = 0;
      card4_ = 0;
      card5_ = 0;
      card6_ = 0;
      card7_ = 0;
      card8_ = 0;
      fuseSkill1_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      fuseSkill2_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      fuseSkill3_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      fuseSkill4_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      proficiency_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard4()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard5()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard6()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard7()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCard8()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuseSkill1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuseSkill2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuseSkill3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuseSkill4()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProficiency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFuseSkill1().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFuseSkill2().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFuseSkill3().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFuseSkill4().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, exp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, card1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, card2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, card3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, card4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, card5_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, card6_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, card7_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, card8_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, fuseSkill1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(11, fuseSkill2_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, fuseSkill3_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeMessage(13, fuseSkill4_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, proficiency_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, exp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, card1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, card2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, card3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, card4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, card5_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, card6_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, card7_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, card8_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, fuseSkill1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, fuseSkill2_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, fuseSkill3_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, fuseSkill4_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, proficiency_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SoulInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SoulInfoMsg)
        com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.internal_static_SoulInfoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.internal_static_SoulInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.class, com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFuseSkill1FieldBuilder();
          getFuseSkill2FieldBuilder();
          getFuseSkill3FieldBuilder();
          getFuseSkill4FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        card1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        card2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        card3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        card4_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        card5_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        card6_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        card7_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        card8_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        if (fuseSkill1Builder_ == null) {
          fuseSkill1_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
        } else {
          fuseSkill1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        if (fuseSkill2Builder_ == null) {
          fuseSkill2_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
        } else {
          fuseSkill2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        if (fuseSkill3Builder_ == null) {
          fuseSkill3_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
        } else {
          fuseSkill3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        if (fuseSkill4Builder_ == null) {
          fuseSkill4_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
        } else {
          fuseSkill4Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        proficiency_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.internal_static_SoulInfoMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg build() {
        com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg result = new com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.card1_ = card1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.card2_ = card2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.card3_ = card3_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.card4_ = card4_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.card5_ = card5_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.card6_ = card6_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.card7_ = card7_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.card8_ = card8_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (fuseSkill1Builder_ == null) {
          result.fuseSkill1_ = fuseSkill1_;
        } else {
          result.fuseSkill1_ = fuseSkill1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (fuseSkill2Builder_ == null) {
          result.fuseSkill2_ = fuseSkill2_;
        } else {
          result.fuseSkill2_ = fuseSkill2Builder_.build();
        }
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        if (fuseSkill3Builder_ == null) {
          result.fuseSkill3_ = fuseSkill3_;
        } else {
          result.fuseSkill3_ = fuseSkill3Builder_.build();
        }
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        if (fuseSkill4Builder_ == null) {
          result.fuseSkill4_ = fuseSkill4_;
        } else {
          result.fuseSkill4_ = fuseSkill4Builder_.build();
        }
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.proficiency_ = proficiency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg.getDefaultInstance()) return this;
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasCard1()) {
          setCard1(other.getCard1());
        }
        if (other.hasCard2()) {
          setCard2(other.getCard2());
        }
        if (other.hasCard3()) {
          setCard3(other.getCard3());
        }
        if (other.hasCard4()) {
          setCard4(other.getCard4());
        }
        if (other.hasCard5()) {
          setCard5(other.getCard5());
        }
        if (other.hasCard6()) {
          setCard6(other.getCard6());
        }
        if (other.hasCard7()) {
          setCard7(other.getCard7());
        }
        if (other.hasCard8()) {
          setCard8(other.getCard8());
        }
        if (other.hasFuseSkill1()) {
          mergeFuseSkill1(other.getFuseSkill1());
        }
        if (other.hasFuseSkill2()) {
          mergeFuseSkill2(other.getFuseSkill2());
        }
        if (other.hasFuseSkill3()) {
          mergeFuseSkill3(other.getFuseSkill3());
        }
        if (other.hasFuseSkill4()) {
          mergeFuseSkill4(other.getFuseSkill4());
        }
        if (other.hasProficiency()) {
          setProficiency(other.getProficiency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExp()) {
          
          return false;
        }
        if (!hasCard1()) {
          
          return false;
        }
        if (!hasCard2()) {
          
          return false;
        }
        if (!hasCard3()) {
          
          return false;
        }
        if (!hasCard4()) {
          
          return false;
        }
        if (!hasCard5()) {
          
          return false;
        }
        if (!hasCard6()) {
          
          return false;
        }
        if (!hasCard7()) {
          
          return false;
        }
        if (!hasCard8()) {
          
          return false;
        }
        if (!hasFuseSkill1()) {
          
          return false;
        }
        if (!hasFuseSkill2()) {
          
          return false;
        }
        if (!hasFuseSkill3()) {
          
          return false;
        }
        if (!hasFuseSkill4()) {
          
          return false;
        }
        if (!hasProficiency()) {
          
          return false;
        }
        if (!getFuseSkill1().isInitialized()) {
          
          return false;
        }
        if (!getFuseSkill2().isInitialized()) {
          
          return false;
        }
        if (!getFuseSkill3().isInitialized()) {
          
          return false;
        }
        if (!getFuseSkill4().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.soul.SoulInfoProto.SoulInfoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long exp_ ;
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *'经验值',
       * </pre>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *'经验值',
       * </pre>
       */
      public long getExp() {
        return exp_;
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *'经验值',
       * </pre>
       */
      public Builder setExp(long value) {
        bitField0_ |= 0x00000001;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *'经验值',
       * </pre>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exp_ = 0L;
        onChanged();
        return this;
      }

      private int card1_ ;
      /**
       * <code>required int32 card1 = 2;</code>
       *
       * <pre>
       * 身上装备的card1--8
       * </pre>
       */
      public boolean hasCard1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 card1 = 2;</code>
       *
       * <pre>
       * 身上装备的card1--8
       * </pre>
       */
      public int getCard1() {
        return card1_;
      }
      /**
       * <code>required int32 card1 = 2;</code>
       *
       * <pre>
       * 身上装备的card1--8
       * </pre>
       */
      public Builder setCard1(int value) {
        bitField0_ |= 0x00000002;
        card1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card1 = 2;</code>
       *
       * <pre>
       * 身上装备的card1--8
       * </pre>
       */
      public Builder clearCard1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        card1_ = 0;
        onChanged();
        return this;
      }

      private int card2_ ;
      /**
       * <code>required int32 card2 = 3;</code>
       */
      public boolean hasCard2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 card2 = 3;</code>
       */
      public int getCard2() {
        return card2_;
      }
      /**
       * <code>required int32 card2 = 3;</code>
       */
      public Builder setCard2(int value) {
        bitField0_ |= 0x00000004;
        card2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card2 = 3;</code>
       */
      public Builder clearCard2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        card2_ = 0;
        onChanged();
        return this;
      }

      private int card3_ ;
      /**
       * <code>required int32 card3 = 4;</code>
       */
      public boolean hasCard3() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 card3 = 4;</code>
       */
      public int getCard3() {
        return card3_;
      }
      /**
       * <code>required int32 card3 = 4;</code>
       */
      public Builder setCard3(int value) {
        bitField0_ |= 0x00000008;
        card3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card3 = 4;</code>
       */
      public Builder clearCard3() {
        bitField0_ = (bitField0_ & ~0x00000008);
        card3_ = 0;
        onChanged();
        return this;
      }

      private int card4_ ;
      /**
       * <code>required int32 card4 = 5;</code>
       */
      public boolean hasCard4() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 card4 = 5;</code>
       */
      public int getCard4() {
        return card4_;
      }
      /**
       * <code>required int32 card4 = 5;</code>
       */
      public Builder setCard4(int value) {
        bitField0_ |= 0x00000010;
        card4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card4 = 5;</code>
       */
      public Builder clearCard4() {
        bitField0_ = (bitField0_ & ~0x00000010);
        card4_ = 0;
        onChanged();
        return this;
      }

      private int card5_ ;
      /**
       * <code>required int32 card5 = 6;</code>
       */
      public boolean hasCard5() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 card5 = 6;</code>
       */
      public int getCard5() {
        return card5_;
      }
      /**
       * <code>required int32 card5 = 6;</code>
       */
      public Builder setCard5(int value) {
        bitField0_ |= 0x00000020;
        card5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card5 = 6;</code>
       */
      public Builder clearCard5() {
        bitField0_ = (bitField0_ & ~0x00000020);
        card5_ = 0;
        onChanged();
        return this;
      }

      private int card6_ ;
      /**
       * <code>required int32 card6 = 7;</code>
       */
      public boolean hasCard6() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 card6 = 7;</code>
       */
      public int getCard6() {
        return card6_;
      }
      /**
       * <code>required int32 card6 = 7;</code>
       */
      public Builder setCard6(int value) {
        bitField0_ |= 0x00000040;
        card6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card6 = 7;</code>
       */
      public Builder clearCard6() {
        bitField0_ = (bitField0_ & ~0x00000040);
        card6_ = 0;
        onChanged();
        return this;
      }

      private int card7_ ;
      /**
       * <code>required int32 card7 = 8;</code>
       */
      public boolean hasCard7() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 card7 = 8;</code>
       */
      public int getCard7() {
        return card7_;
      }
      /**
       * <code>required int32 card7 = 8;</code>
       */
      public Builder setCard7(int value) {
        bitField0_ |= 0x00000080;
        card7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card7 = 8;</code>
       */
      public Builder clearCard7() {
        bitField0_ = (bitField0_ & ~0x00000080);
        card7_ = 0;
        onChanged();
        return this;
      }

      private int card8_ ;
      /**
       * <code>required int32 card8 = 9;</code>
       */
      public boolean hasCard8() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 card8 = 9;</code>
       */
      public int getCard8() {
        return card8_;
      }
      /**
       * <code>required int32 card8 = 9;</code>
       */
      public Builder setCard8(int value) {
        bitField0_ |= 0x00000100;
        card8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 card8 = 9;</code>
       */
      public Builder clearCard8() {
        bitField0_ = (bitField0_ & ~0x00000100);
        card8_ = 0;
        onChanged();
        return this;
      }

      private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill1_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> fuseSkill1Builder_;
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public boolean hasFuseSkill1() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill1() {
        if (fuseSkill1Builder_ == null) {
          return fuseSkill1_;
        } else {
          return fuseSkill1Builder_.getMessage();
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public Builder setFuseSkill1(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuseSkill1_ = value;
          onChanged();
        } else {
          fuseSkill1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public Builder setFuseSkill1(
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder builderForValue) {
        if (fuseSkill1Builder_ == null) {
          fuseSkill1_ = builderForValue.build();
          onChanged();
        } else {
          fuseSkill1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public Builder mergeFuseSkill1(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill1Builder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              fuseSkill1_ != com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance()) {
            fuseSkill1_ =
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.newBuilder(fuseSkill1_).mergeFrom(value).buildPartial();
          } else {
            fuseSkill1_ = value;
          }
          onChanged();
        } else {
          fuseSkill1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public Builder clearFuseSkill1() {
        if (fuseSkill1Builder_ == null) {
          fuseSkill1_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
          onChanged();
        } else {
          fuseSkill1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder getFuseSkill1Builder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getFuseSkill1FieldBuilder().getBuilder();
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill1OrBuilder() {
        if (fuseSkill1Builder_ != null) {
          return fuseSkill1Builder_.getMessageOrBuilder();
        } else {
          return fuseSkill1_;
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill1 = 10;</code>
       *
       * <pre>
       *融合技能1--4
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> 
          getFuseSkill1FieldBuilder() {
        if (fuseSkill1Builder_ == null) {
          fuseSkill1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder>(
                  getFuseSkill1(),
                  getParentForChildren(),
                  isClean());
          fuseSkill1_ = null;
        }
        return fuseSkill1Builder_;
      }

      private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill2_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> fuseSkill2Builder_;
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public boolean hasFuseSkill2() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill2() {
        if (fuseSkill2Builder_ == null) {
          return fuseSkill2_;
        } else {
          return fuseSkill2Builder_.getMessage();
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public Builder setFuseSkill2(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuseSkill2_ = value;
          onChanged();
        } else {
          fuseSkill2Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public Builder setFuseSkill2(
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder builderForValue) {
        if (fuseSkill2Builder_ == null) {
          fuseSkill2_ = builderForValue.build();
          onChanged();
        } else {
          fuseSkill2Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public Builder mergeFuseSkill2(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill2Builder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              fuseSkill2_ != com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance()) {
            fuseSkill2_ =
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.newBuilder(fuseSkill2_).mergeFrom(value).buildPartial();
          } else {
            fuseSkill2_ = value;
          }
          onChanged();
        } else {
          fuseSkill2Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public Builder clearFuseSkill2() {
        if (fuseSkill2Builder_ == null) {
          fuseSkill2_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
          onChanged();
        } else {
          fuseSkill2Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder getFuseSkill2Builder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getFuseSkill2FieldBuilder().getBuilder();
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill2OrBuilder() {
        if (fuseSkill2Builder_ != null) {
          return fuseSkill2Builder_.getMessageOrBuilder();
        } else {
          return fuseSkill2_;
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill2 = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> 
          getFuseSkill2FieldBuilder() {
        if (fuseSkill2Builder_ == null) {
          fuseSkill2Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder>(
                  getFuseSkill2(),
                  getParentForChildren(),
                  isClean());
          fuseSkill2_ = null;
        }
        return fuseSkill2Builder_;
      }

      private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill3_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> fuseSkill3Builder_;
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public boolean hasFuseSkill3() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill3() {
        if (fuseSkill3Builder_ == null) {
          return fuseSkill3_;
        } else {
          return fuseSkill3Builder_.getMessage();
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public Builder setFuseSkill3(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuseSkill3_ = value;
          onChanged();
        } else {
          fuseSkill3Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public Builder setFuseSkill3(
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder builderForValue) {
        if (fuseSkill3Builder_ == null) {
          fuseSkill3_ = builderForValue.build();
          onChanged();
        } else {
          fuseSkill3Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public Builder mergeFuseSkill3(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill3Builder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800) &&
              fuseSkill3_ != com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance()) {
            fuseSkill3_ =
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.newBuilder(fuseSkill3_).mergeFrom(value).buildPartial();
          } else {
            fuseSkill3_ = value;
          }
          onChanged();
        } else {
          fuseSkill3Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public Builder clearFuseSkill3() {
        if (fuseSkill3Builder_ == null) {
          fuseSkill3_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
          onChanged();
        } else {
          fuseSkill3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder getFuseSkill3Builder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getFuseSkill3FieldBuilder().getBuilder();
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill3OrBuilder() {
        if (fuseSkill3Builder_ != null) {
          return fuseSkill3Builder_.getMessageOrBuilder();
        } else {
          return fuseSkill3_;
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill3 = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> 
          getFuseSkill3FieldBuilder() {
        if (fuseSkill3Builder_ == null) {
          fuseSkill3Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder>(
                  getFuseSkill3(),
                  getParentForChildren(),
                  isClean());
          fuseSkill3_ = null;
        }
        return fuseSkill3Builder_;
      }

      private com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg fuseSkill4_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> fuseSkill4Builder_;
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public boolean hasFuseSkill4() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg getFuseSkill4() {
        if (fuseSkill4Builder_ == null) {
          return fuseSkill4_;
        } else {
          return fuseSkill4Builder_.getMessage();
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public Builder setFuseSkill4(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill4Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuseSkill4_ = value;
          onChanged();
        } else {
          fuseSkill4Builder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public Builder setFuseSkill4(
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder builderForValue) {
        if (fuseSkill4Builder_ == null) {
          fuseSkill4_ = builderForValue.build();
          onChanged();
        } else {
          fuseSkill4Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public Builder mergeFuseSkill4(com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg value) {
        if (fuseSkill4Builder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000) &&
              fuseSkill4_ != com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance()) {
            fuseSkill4_ =
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.newBuilder(fuseSkill4_).mergeFrom(value).buildPartial();
          } else {
            fuseSkill4_ = value;
          }
          onChanged();
        } else {
          fuseSkill4Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public Builder clearFuseSkill4() {
        if (fuseSkill4Builder_ == null) {
          fuseSkill4_ = com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.getDefaultInstance();
          onChanged();
        } else {
          fuseSkill4Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder getFuseSkill4Builder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getFuseSkill4FieldBuilder().getBuilder();
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      public com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder getFuseSkill4OrBuilder() {
        if (fuseSkill4Builder_ != null) {
          return fuseSkill4Builder_.getMessageOrBuilder();
        } else {
          return fuseSkill4_;
        }
      }
      /**
       * <code>required .FuseSkillMsg fuseSkill4 = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder> 
          getFuseSkill4FieldBuilder() {
        if (fuseSkill4Builder_ == null) {
          fuseSkill4Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsg.Builder, com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.FuseSkillMsgOrBuilder>(
                  getFuseSkill4(),
                  getParentForChildren(),
                  isClean());
          fuseSkill4_ = null;
        }
        return fuseSkill4Builder_;
      }

      private int proficiency_ ;
      /**
       * <code>required int32 proficiency = 14;</code>
       *
       * <pre>
       *制作熟悉度
       * </pre>
       */
      public boolean hasProficiency() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 proficiency = 14;</code>
       *
       * <pre>
       *制作熟悉度
       * </pre>
       */
      public int getProficiency() {
        return proficiency_;
      }
      /**
       * <code>required int32 proficiency = 14;</code>
       *
       * <pre>
       *制作熟悉度
       * </pre>
       */
      public Builder setProficiency(int value) {
        bitField0_ |= 0x00002000;
        proficiency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 proficiency = 14;</code>
       *
       * <pre>
       *制作熟悉度
       * </pre>
       */
      public Builder clearProficiency() {
        bitField0_ = (bitField0_ & ~0x00002000);
        proficiency_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SoulInfoMsg)
    }

    static {
      defaultInstance = new SoulInfoMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SoulInfoMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoulInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SoulInfoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026soul/SoulInfoMsg.proto\032\027soul/FuseSkill" +
      "Msg.proto\"\263\002\n\013SoulInfoMsg\022\013\n\003exp\030\001 \002(\003\022\r" +
      "\n\005card1\030\002 \002(\005\022\r\n\005card2\030\003 \002(\005\022\r\n\005card3\030\004 " +
      "\002(\005\022\r\n\005card4\030\005 \002(\005\022\r\n\005card5\030\006 \002(\005\022\r\n\005car" +
      "d6\030\007 \002(\005\022\r\n\005card7\030\010 \002(\005\022\r\n\005card8\030\t \002(\005\022!" +
      "\n\nfuseSkill1\030\n \002(\0132\r.FuseSkillMsg\022!\n\nfus" +
      "eSkill2\030\013 \002(\0132\r.FuseSkillMsg\022!\n\nfuseSkil" +
      "l3\030\014 \002(\0132\r.FuseSkillMsg\022!\n\nfuseSkill4\030\r " +
      "\002(\0132\r.FuseSkillMsg\022\023\n\013proficiency\030\016 \002(\005B" +
      "6\n%com.chuangyou.common.protobuf.pb.soul",
      "B\rSoulInfoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.getDescriptor(),
        }, assigner);
    internal_static_SoulInfoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SoulInfoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SoulInfoMsg_descriptor,
        new java.lang.String[] { "Exp", "Card1", "Card2", "Card3", "Card4", "Card5", "Card6", "Card7", "Card8", "FuseSkill1", "FuseSkill2", "FuseSkill3", "FuseSkill4", "Proficiency", });
    com.chuangyou.common.protobuf.pb.soul.FuseSkillProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
