// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mount/MountGradeUpRespMsg.proto

package com.chuangyou.common.protobuf.pb.mount;

public final class MountGradeUpRespProto {
  private MountGradeUpRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MountGradeUpRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MountGradeUpRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 grade = 1;</code>
     *
     * <pre>
     * 坐骑进阶等级
     * </pre>
     */
    boolean hasGrade();
    /**
     * <code>optional int32 grade = 1;</code>
     *
     * <pre>
     * 坐骑进阶等级
     * </pre>
     */
    int getGrade();

    /**
     * <code>optional int32 bless = 2;</code>
     *
     * <pre>
     * 坐骑进阶祝福值
     * </pre>
     */
    boolean hasBless();
    /**
     * <code>optional int32 bless = 2;</code>
     *
     * <pre>
     * 坐骑进阶祝福值
     * </pre>
     */
    int getBless();
  }
  /**
   * Protobuf type {@code MountGradeUpRespMsg}
   */
  public static final class MountGradeUpRespMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MountGradeUpRespMsg)
      MountGradeUpRespMsgOrBuilder {
    // Use MountGradeUpRespMsg.newBuilder() to construct.
    private MountGradeUpRespMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MountGradeUpRespMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MountGradeUpRespMsg defaultInstance;
    public static MountGradeUpRespMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MountGradeUpRespMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MountGradeUpRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              grade_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              bless_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.internal_static_MountGradeUpRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.internal_static_MountGradeUpRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.class, com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MountGradeUpRespMsg> PARSER =
        new com.google.protobuf.AbstractParser<MountGradeUpRespMsg>() {
      public MountGradeUpRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MountGradeUpRespMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MountGradeUpRespMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GRADE_FIELD_NUMBER = 1;
    private int grade_;
    /**
     * <code>optional int32 grade = 1;</code>
     *
     * <pre>
     * 坐骑进阶等级
     * </pre>
     */
    public boolean hasGrade() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 grade = 1;</code>
     *
     * <pre>
     * 坐骑进阶等级
     * </pre>
     */
    public int getGrade() {
      return grade_;
    }

    public static final int BLESS_FIELD_NUMBER = 2;
    private int bless_;
    /**
     * <code>optional int32 bless = 2;</code>
     *
     * <pre>
     * 坐骑进阶祝福值
     * </pre>
     */
    public boolean hasBless() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 bless = 2;</code>
     *
     * <pre>
     * 坐骑进阶祝福值
     * </pre>
     */
    public int getBless() {
      return bless_;
    }

    private void initFields() {
      grade_ = 0;
      bless_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, grade_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, bless_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, grade_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bless_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MountGradeUpRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MountGradeUpRespMsg)
        com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.internal_static_MountGradeUpRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.internal_static_MountGradeUpRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.class, com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.Builder.class);
      }

      // Construct using com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        grade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        bless_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.internal_static_MountGradeUpRespMsg_descriptor;
      }

      public com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg getDefaultInstanceForType() {
        return com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.getDefaultInstance();
      }

      public com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg build() {
        com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg buildPartial() {
        com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg result = new com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.grade_ = grade_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bless_ = bless_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg) {
          return mergeFrom((com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg other) {
        if (other == com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg.getDefaultInstance()) return this;
        if (other.hasGrade()) {
          setGrade(other.getGrade());
        }
        if (other.hasBless()) {
          setBless(other.getBless());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chuangyou.common.protobuf.pb.mount.MountGradeUpRespProto.MountGradeUpRespMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int grade_ ;
      /**
       * <code>optional int32 grade = 1;</code>
       *
       * <pre>
       * 坐骑进阶等级
       * </pre>
       */
      public boolean hasGrade() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 grade = 1;</code>
       *
       * <pre>
       * 坐骑进阶等级
       * </pre>
       */
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>optional int32 grade = 1;</code>
       *
       * <pre>
       * 坐骑进阶等级
       * </pre>
       */
      public Builder setGrade(int value) {
        bitField0_ |= 0x00000001;
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 grade = 1;</code>
       *
       * <pre>
       * 坐骑进阶等级
       * </pre>
       */
      public Builder clearGrade() {
        bitField0_ = (bitField0_ & ~0x00000001);
        grade_ = 0;
        onChanged();
        return this;
      }

      private int bless_ ;
      /**
       * <code>optional int32 bless = 2;</code>
       *
       * <pre>
       * 坐骑进阶祝福值
       * </pre>
       */
      public boolean hasBless() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 bless = 2;</code>
       *
       * <pre>
       * 坐骑进阶祝福值
       * </pre>
       */
      public int getBless() {
        return bless_;
      }
      /**
       * <code>optional int32 bless = 2;</code>
       *
       * <pre>
       * 坐骑进阶祝福值
       * </pre>
       */
      public Builder setBless(int value) {
        bitField0_ |= 0x00000002;
        bless_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bless = 2;</code>
       *
       * <pre>
       * 坐骑进阶祝福值
       * </pre>
       */
      public Builder clearBless() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bless_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MountGradeUpRespMsg)
    }

    static {
      defaultInstance = new MountGradeUpRespMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MountGradeUpRespMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MountGradeUpRespMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MountGradeUpRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mount/MountGradeUpRespMsg.proto\"3\n\023Mou" +
      "ntGradeUpRespMsg\022\r\n\005grade\030\001 \001(\005\022\r\n\005bless" +
      "\030\002 \001(\005B?\n&com.chuangyou.common.protobuf." +
      "pb.mountB\025MountGradeUpRespProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MountGradeUpRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MountGradeUpRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MountGradeUpRespMsg_descriptor,
        new java.lang.String[] { "Grade", "Bless", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
